PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE company (
  company_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);
INSERT INTO company VALUES(1,'Nintendo Co., Ltd.');
INSERT INTO company VALUES(2,'Square Co., Ltd.');
INSERT INTO company VALUES(3,'Square Enix Co., Ltd.');
INSERT INTO company VALUES(4,'Square Enix Limited');
INSERT INTO company VALUES(5,'Square Enix Ltd');
INSERT INTO company VALUES(6,'Square Enix, Inc.');
INSERT INTO company VALUES(7,'Square Soft, Inc.');
INSERT INTO company VALUES(8,'Sony Computer Entertainment America LLC');
INSERT INTO company VALUES(9,'Nintendo R&D1');
INSERT INTO company VALUES(10,'Intelligent Systems Co., Ltd.');
INSERT INTO company VALUES(11,'Nintendo EAD');
INSERT INTO company VALUES(12,'Nintendo of America Inc.');
INSERT INTO company VALUES(13,'Nintendo of Europe GmbH');
INSERT INTO company VALUES(14,'Sony Computer Entertainment Europe Ltd.');
INSERT INTO company VALUES(15,'Rare Limited');
INSERT INTO company VALUES(16,'Capcom Co., Ltd.');
INSERT INTO company VALUES(17,'SEGA Enterprises Ltd.');
INSERT INTO company VALUES(18,'U.S. Gold Ltd.');
INSERT INTO company VALUES(19,'Hitmen Productions');
INSERT INTO company VALUES(20,'Electronic Arts, Inc.');
INSERT INTO company VALUES(21,'HAL Laboratory, Inc.');
INSERT INTO company VALUES(22,'Ape');
INSERT INTO company VALUES(23,'Quest Corporation');
INSERT INTO company VALUES(24,'Artdink Corporation');
INSERT INTO company VALUES(25,'Riverhill Soft Inc.');
INSERT INTO company VALUES(26,'Atlus Software Inc.');
INSERT INTO company VALUES(27,'Konami Co., Ltd.');
INSERT INTO company VALUES(28,'Konami Digital Entertainment Co., Ltd.');
INSERT INTO company VALUES(29,'Nintendo Australia Pty., Ltd.');
INSERT INTO company VALUES(30,'Konami Industry Co. Ltd.');
INSERT INTO company VALUES(31,'Palcom Software Ltd.');
INSERT INTO company VALUES(32,'Midway Manufacturing Company');
INSERT INTO company VALUES(33,'Tec Toy Indústria de Brinquedos S.A.');
INSERT INTO company VALUES(34,'Acclaim Entertainment, Inc.');
INSERT INTO company VALUES(35,'Atari Corporation');
INSERT INTO company VALUES(36,'Capcom Mobile, Inc.');
INSERT INTO company VALUES(37,'Produce Co., Ltd.');
INSERT INTO company VALUES(38,'Hudson Soft Company, Ltd.');
INSERT INTO company VALUES(39,'Virgin Interactive Entertainment SARL');
INSERT INTO company VALUES(40,'Virgin Interactive Entertainment (Deutschland) GmbH');
INSERT INTO company VALUES(41,'Visual Concepts Entertainment, Inc.');
INSERT INTO company VALUES(42,'High Score Productions');
INSERT INTO company VALUES(43,'Playtronic Industrial Ltda.');
INSERT INTO company VALUES(44,'Major A');
INSERT INTO company VALUES(45,'Konami Computer Entertainment Osaka Co., Ltd.');
INSERT INTO company VALUES(46,'Electronic Arts Canada');
INSERT INTO company VALUES(47,'Sony Computer Entertainment America Inc.');
INSERT INTO company VALUES(48,'Blizzard Entertainment Inc.');
INSERT INTO company VALUES(49,'Silicon & Synapse, Inc.');
INSERT INTO company VALUES(50,'Interplay Productions, Inc.');
INSERT INTO company VALUES(51,'Namco Limited');
INSERT INTO company VALUES(52,'Vivendi Universal Games, Inc.');
INSERT INTO company VALUES(53,'Software Creations Ltd.');
INSERT INTO company VALUES(54,'Sony Imagesoft');
INSERT INTO company VALUES(55,'Sony Music Entertainment (Japan), Inc.');
INSERT INTO company VALUES(56,'Quintet Co., Ltd.');
INSERT INTO company VALUES(57,'Enix Corporation');
INSERT INTO company VALUES(58,'Irem Corp.');
INSERT INTO company VALUES(59,'Jaleco USA, Inc.');
INSERT INTO company VALUES(60,'Destination Software, Inc.');
INSERT INTO company VALUES(61,'Jaleco Entertainment, Inc.');
INSERT INTO company VALUES(62,'Irem Software Engineering, Inc.');
INSERT INTO company VALUES(63,'ZOO Digital Publishing Ltd.');
INSERT INTO company VALUES(64,'DMA Design Limited');
INSERT INTO company VALUES(65,'FRED Publishing');
INSERT INTO company VALUES(66,'Philips Interactive Media, Inc.');
INSERT INTO company VALUES(67,'iFone');
INSERT INTO company VALUES(68,'Imagineer Co., Ltd.');
INSERT INTO company VALUES(69,'Krisalis Software Ltd.');
INSERT INTO company VALUES(70,'Psygnosis Limited');
INSERT INTO company VALUES(71,'Sun Electronics Corp.');
INSERT INTO company VALUES(72,'Electronic Arts Victor, Inc.');
INSERT INTO company VALUES(73,'Ocean Software Ltd.');
INSERT INTO company VALUES(74,'Enix America Corporation');
INSERT INTO company VALUES(75,'Blue Byte Software GmbH');
INSERT INTO company VALUES(76,'Ubi Soft Entertainment Software');
INSERT INTO company VALUES(77,'Misawa Entertainment Co.,Ltd.');
INSERT INTO company VALUES(78,'Laguna Video Games');
INSERT INTO company VALUES(79,'Laguna Videospiele Vertriebs & Marketing GmbH');
INSERT INTO company VALUES(80,'Compile');
INSERT INTO company VALUES(81,'Toho Co., Ltd.');
INSERT INTO company VALUES(82,'NCS Corporation');
INSERT INTO company VALUES(83,'505 GameStreet');
INSERT INTO company VALUES(84,'Hudson Entertainment, Inc.');
INSERT INTO company VALUES(85,'X-Naut.Psikyo');
INSERT INTO company VALUES(86,'Konami Deutschland GmbH');
INSERT INTO company VALUES(87,'Konami, Inc.');
INSERT INTO company VALUES(88,'Konami Digital Entertainment, Inc.');
INSERT INTO company VALUES(89,'WindySoft Co., Ltd.');
INSERT INTO company VALUES(90,'Natsume Co., Ltd.');
INSERT INTO company VALUES(91,'Natsume, Inc.');
INSERT INTO company VALUES(92,'Titus France SA');
INSERT INTO company VALUES(93,'Konami Digital Entertainment GmbH');
INSERT INTO company VALUES(94,'Brøderbund Software, Inc.');
INSERT INTO company VALUES(95,'Arsys Software, Inc.');
INSERT INTO company VALUES(96,'Revelation Software');
INSERT INTO company VALUES(97,'Turbo Technologies, Inc.');
INSERT INTO company VALUES(98,'Virgin Games, Inc.');
INSERT INTO company VALUES(99,'Mindscape International Ltd.');
INSERT INTO company VALUES(100,'Ubisoft Entertainment SA');
INSERT INTO company VALUES(101,'Victor Musical Industries, Inc.');
INSERT INTO company VALUES(102,'Softgold Computerspiele GmbH');
INSERT INTO company VALUES(103,'Tengen Inc.');
INSERT INTO company VALUES(104,'Domark Software Ltd.');
INSERT INTO company VALUES(105,'Factor 5 GmbH');
INSERT INTO company VALUES(106,'Maxis Software Inc.');
INSERT INTO company VALUES(107,'Atelier Software S.A.');
INSERT INTO company VALUES(108,'Erbe Software, S.A.');
INSERT INTO company VALUES(109,'Enfour, Inc.');
INSERT INTO company VALUES(110,'DUX Software Corporation');
INSERT INTO company VALUES(111,'Superior Software Ltd.');
INSERT INTO company VALUES(112,'Infogrames Europe SA');
INSERT INTO company VALUES(113,'Foretune Co., Ltd.');
INSERT INTO company VALUES(114,'Fujitsu Limited');
INSERT INTO company VALUES(115,'Neverland Co., Ltd.');
INSERT INTO company VALUES(116,'Taito Corporation');
INSERT INTO company VALUES(117,'Virgin Interactive Entertainment (Europe) Ltd.');
INSERT INTO company VALUES(118,'Vivid Image');
INSERT INTO company VALUES(119,'Acid Software');
INSERT INTO company VALUES(120,'Piko Interactive LLC');
INSERT INTO company VALUES(121,'Konami (America), Inc.');
INSERT INTO company VALUES(122,'Sensible Software');
INSERT INTO company VALUES(123,'Shiny Entertainment, Inc.');
INSERT INTO company VALUES(124,'THQ Inc.');
INSERT INTO company VALUES(125,'Playmates Interactive Entertainment, Inc.');
INSERT INTO company VALUES(126,'Interplay Entertainment Corp.');
INSERT INTO company VALUES(127,'Majesco Sales, Inc.');
INSERT INTO company VALUES(128,'TAKARA Co., Ltd.');
INSERT INTO company VALUES(129,'Activision, Inc.');
INSERT INTO company VALUES(130,'Konami UK Ltd.');
INSERT INTO company VALUES(131,'Konami of Europe GmbH');
INSERT INTO company VALUES(132,'Delphine Software International');
INSERT INTO company VALUES(133,'Eidos Interactive Limited');
INSERT INTO company VALUES(134,'SoftKey Multimedia Inc.');
INSERT INTO company VALUES(135,'Strategic Simulations, Inc.');
INSERT INTO company VALUES(136,'JoshProd');
INSERT INTO company VALUES(137,'Manomio LLC');
INSERT INTO company VALUES(138,'Victor Entertainment Inc.');
INSERT INTO company VALUES(139,'MacPlay');
INSERT INTO company VALUES(140,'Gremlin Graphics Software Limited');
INSERT INTO company VALUES(141,'Kotobuki System Co., Ltd.');
INSERT INTO company VALUES(142,'Kemco America, Inc.');
INSERT INTO company VALUES(143,'Disney Software');
INSERT INTO company VALUES(144,'Matsushita Electric Corporation of America');
INSERT INTO company VALUES(145,'GameBank Corp.');
INSERT INTO company VALUES(146,'SEGA of America, Inc.');
INSERT INTO company VALUES(147,'MediaKite Distribution Inc.');
INSERT INTO company VALUES(148,'Matsushita Electric Industrial Co., Ltd.');
INSERT INTO company VALUES(149,'CyberFront Corporation');
INSERT INTO company VALUES(150,'Sun Corporation');
INSERT INTO company VALUES(151,'Winky Soft Co., Ltd.');
INSERT INTO company VALUES(152,'Zamuse');
INSERT INTO company VALUES(153,'Extended Play Productions');
INSERT INTO company VALUES(154,'Malibu Games');
INSERT INTO company VALUES(155,'Human Entertainment, Inc.');
INSERT INTO company VALUES(156,'Kaga Tech Co., Ltd.');
INSERT INTO company VALUES(157,'Argonaut Software Ltd.');
INSERT INTO company VALUES(158,'Virgin Interactive Entertainment, Inc.');
INSERT INTO company VALUES(159,'Sony Computer Entertainment Inc.');
INSERT INTO company VALUES(160,'MicroMouse Co., Ltd.');
INSERT INTO company VALUES(161,'Ukiyotei Company, Ltd.');
INSERT INTO company VALUES(162,'Sony Imagesoft UK');
INSERT INTO company VALUES(163,'Sony Electronic Publishing Ltd.');
INSERT INTO company VALUES(164,'Nintendo R&D3');
INSERT INTO company VALUES(165,'Sculptured Software, Inc.');
INSERT INTO company VALUES(166,'Realtime Associates Seattle Division');
INSERT INTO company VALUES(167,'LucasArts Entertainment Company LLC');
INSERT INTO company VALUES(168,'LucasArts');
INSERT INTO company VALUES(169,'Black Pearl Software');
INSERT INTO company VALUES(170,'JVC Musical Industries, Inc.');
INSERT INTO company VALUES(171,'CAProduction Co., Ltd.');
INSERT INTO company VALUES(172,'Red Company Corporation');
INSERT INTO company VALUES(173,'Hudson Soft Europe Limited');
INSERT INTO company VALUES(174,'Hudson Soft USA, Inc.');
INSERT INTO company VALUES(175,'Rage Software Ltd.');
INSERT INTO company VALUES(176,'G.X. Media Co., Ltd.');
INSERT INTO company VALUES(177,'Elite Systems Ltd.');
INSERT INTO company VALUES(178,'Gremlin Interactive Limited');
INSERT INTO company VALUES(179,'Konami Digital Entertainment B.V.');
INSERT INTO company VALUES(180,'SOFEL Co., Ltd.');
INSERT INTO company VALUES(181,'Infogrames, Inc.');
INSERT INTO company VALUES(182,'Atari Europe S.A.S.U.');
INSERT INTO company VALUES(183,'d&d Corp.');
INSERT INTO company VALUES(184,'Tose Co., Ltd.');
INSERT INTO company VALUES(185,'BANDAI NAMCO Entertainment Inc.');
INSERT INTO company VALUES(186,'Bandai Co., Ltd.');
INSERT INTO company VALUES(187,'Chunsoft Co., Ltd.');
INSERT INTO company VALUES(188,'Williams Electronics Games, Inc.');
INSERT INTO company VALUES(189,'Flying Edge, Inc.');
INSERT INTO company VALUES(190,'Warner Bros. Interactive Entertainment Inc.');
INSERT INTO company VALUES(191,'Midway Home Entertainment, Inc.');
INSERT INTO company VALUES(192,'ASCII Corporation');
INSERT INTO company VALUES(193,'Tecmo, Inc.');
INSERT INTO company VALUES(194,'Tecmo, Ltd.');
INSERT INTO company VALUES(195,'Williams Entertainment, Inc.');
INSERT INTO company VALUES(196,'Sony Computer Entertainment of America');
INSERT INTO company VALUES(197,'G-Craft');
INSERT INTO company VALUES(198,'Tokyo Shoseki Co., Ltd.');
INSERT INTO company VALUES(199,'Westwood Studios, Inc.');
INSERT INTO company VALUES(200,'Denton Designs');
INSERT INTO company VALUES(201,'GameTek, Inc.');
INSERT INTO company VALUES(202,'Beam Software Pty., Ltd.');
INSERT INTO company VALUES(203,'Hudson Soft Europe GmbH');
INSERT INTO company VALUES(204,'Factor 5, Inc.');
INSERT INTO company VALUES(205,'Seika Corporation');
INSERT INTO company VALUES(206,'Wolf Team');
INSERT INTO company VALUES(207,'Tradewest, Inc.');
INSERT INTO company VALUES(208,'Activision Japan Co., Ltd.');
INSERT INTO company VALUES(209,'Prism Kikaku Ltd.');
INSERT INTO company VALUES(210,'Hori Electric Co., Ltd.');
INSERT INTO company VALUES(211,'Tiburon Entertainment');
INSERT INTO company VALUES(212,'SCi Games Ltd.');
INSERT INTO company VALUES(213,'Sales Curve Ltd., The');
INSERT INTO company VALUES(214,'Sun Corporation of America');
INSERT INTO company VALUES(215,'Coconuts Japan Entertainment Co., Ltd.');
INSERT INTO company VALUES(216,'Time Warner Interactive Inc.');
INSERT INTO company VALUES(217,'Activision Publishing, Inc.');
INSERT INTO company VALUES(218,'Pony Canyon, Inc.');
INSERT INTO company VALUES(219,'Iguana Entertainment Incorporated');
INSERT INTO company VALUES(220,'Bullfrog Productions, Ltd.');
INSERT INTO company VALUES(221,'EA Studios Japan');
INSERT INTO company VALUES(222,'Novitas GmbH');
INSERT INTO company VALUES(223,'Mindscape, Inc.');
INSERT INTO company VALUES(224,'LJN, Ltd.');
INSERT INTO company VALUES(225,'Granite Bay Software');
INSERT INTO company VALUES(226,'Telegames, Inc.');
INSERT INTO company VALUES(227,'Amiga, Inc.');
INSERT INTO company VALUES(228,'Celestial Software');
INSERT INTO company VALUES(229,'GameTek (FL), Inc.');
INSERT INTO company VALUES(230,'Epic/Sony Inc.');
INSERT INTO company VALUES(231,'Data East Corporation');
INSERT INTO company VALUES(232,'Data East USA, Inc.');
INSERT INTO company VALUES(233,'Laser Beam Entertainment Pty. Ltd.');
INSERT INTO company VALUES(234,'Hamster Corporation');
INSERT INTO company VALUES(235,'Probe Software Ltd.');
INSERT INTO company VALUES(236,'Spearsoft');
INSERT INTO company VALUES(237,'Dice Multi Media Europe B.V.');
INSERT INTO company VALUES(238,'Disney Interactive, Inc.');
INSERT INTO company VALUES(239,'Disney Interactive Studios, Inc.');
INSERT INTO company VALUES(240,'Activision (UK) Limited');
INSERT INTO company VALUES(241,'ASCII Entertainment Software, Inc.');
INSERT INTO company VALUES(242,'Electric Dreams Software');
INSERT INTO company VALUES(243,'Vic Tokai, Inc.');
INSERT INTO company VALUES(244,'Double Diamond Sports');
INSERT INTO company VALUES(245,'Park Place Productions');
INSERT INTO company VALUES(246,'Pioneer Productions');
INSERT INTO company VALUES(247,'T&E Soft, Inc.');
INSERT INTO company VALUES(248,'Accolade, Inc.');
INSERT INTO company VALUES(249,'Nintendo UK Entertainment Limited');
INSERT INTO company VALUES(250,'Amccus');
INSERT INTO company VALUES(251,'Pack-In-Video Co., Ltd');
INSERT INTO company VALUES(252,'Marvelous Entertainment Inc.');
INSERT INTO company VALUES(253,'Marvelous Inc.');
INSERT INTO company VALUES(254,'Lay-Up KK');
INSERT INTO company VALUES(255,'tri-Ace Inc.');
INSERT INTO company VALUES(256,'JVC Musical Industries Europe, Ltd.');
INSERT INTO company VALUES(257,'Jupiter Corp.');
INSERT INTO company VALUES(258,'Tiertex Ltd.');
INSERT INTO company VALUES(259,'Tiertex Design Studios');
INSERT INTO company VALUES(260,'Poppo Co., Ltd.');
INSERT INTO company VALUES(261,'Bullet-Proof Software, Inc.');
INSERT INTO company VALUES(262,'SNK Playmore Corporation');
INSERT INTO company VALUES(263,'SNK Corporation');
INSERT INTO company VALUES(264,'BMG Japan Inc.');
INSERT INTO company VALUES(265,'D4 Enterprise, Inc.');
INSERT INTO company VALUES(266,'Crystal Dynamics, Inc.');
INSERT INTO company VALUES(267,'Japan Home Video Co. Ltd.');
INSERT INTO company VALUES(268,'Titus Interactive, S.A.');
INSERT INTO company VALUES(269,'Arc System Works Co., Ltd.');
INSERT INTO company VALUES(270,'Titus Software Corporation');
INSERT INTO company VALUES(271,'Disney Games');
INSERT INTO company VALUES(272,'Core Design Ltd.');
INSERT INTO company VALUES(273,'SEGA Europe Ltd.');
INSERT INTO company VALUES(274,'Corkers');
INSERT INTO company VALUES(275,'Genias');
INSERT INTO company VALUES(276,'Virgin Games, Ltd.');
INSERT INTO company VALUES(277,'Viacom New Media');
INSERT INTO company VALUES(278,'Traveller''s Tales (UK) Ltd.');
INSERT INTO company VALUES(279,'Disney Mobile');
INSERT INTO company VALUES(280,'MicroProse Software, Inc.');
INSERT INTO company VALUES(281,'MPS Labs');
INSERT INTO company VALUES(282,'Asmik Corporation');
INSERT INTO company VALUES(283,'Hasbro Interactive, Inc.');
INSERT INTO company VALUES(284,'Asmik Ace Entertainment, Inc.');
INSERT INTO company VALUES(285,'Software Demon');
INSERT INTO company VALUES(286,'KOEI Corporation');
INSERT INTO company VALUES(287,'Atlus Co., Ltd.');
INSERT INTO company VALUES(288,'Index Corporation');
INSERT INTO company VALUES(289,'SIMS Co., Ltd.');
INSERT INTO company VALUES(290,'Video System Co., Ltd.');
INSERT INTO company VALUES(291,'McO''RIVER Inc.');
INSERT INTO company VALUES(292,'Virgin Interactive Entertainment (Japan), Inc.');
INSERT INTO company VALUES(293,'Infogrames Multimedia SA');
INSERT INTO company VALUES(294,'A.I Co., Ltd.');
INSERT INTO company VALUES(295,'Telcogames Ltd.');
INSERT INTO company VALUES(296,'RGC');
INSERT INTO company VALUES(297,'Magic Productions');
INSERT INTO company VALUES(298,'Akella');
INSERT INTO company VALUES(299,'Interplay Productions Ltd.');
INSERT INTO company VALUES(300,'Walt Disney Computer Software, Inc.');
INSERT INTO company VALUES(301,'The Codemasters Software Company Limited');
INSERT INTO company VALUES(302,'naxat Co., Ltd.');
INSERT INTO company VALUES(303,'CSK Research Institute Corp.');
INSERT INTO company VALUES(304,'Mirrorsoft Ltd.');
INSERT INTO company VALUES(305,'Namcot');
INSERT INTO company VALUES(306,'Omiya Soft, Co. Ltd.');
INSERT INTO company VALUES(307,'Cobra Team');
INSERT INTO company VALUES(308,'Atod Design KB');
INSERT INTO company VALUES(309,'Success Corp.');
INSERT INTO company VALUES(310,'ININ Games, Softdistribution');
INSERT INTO company VALUES(311,'Datam Polystar Co.,Ltd.');
INSERT INTO company VALUES(312,'United Games Entertainment GmbH');
INSERT INTO company VALUES(313,'Kuju Wireless Publishing Ltd.');
INSERT INTO company VALUES(314,'Codemasters');
INSERT INTO company VALUES(315,'Sold Out Sales & Marketing Ltd.');
INSERT INTO company VALUES(316,'Irem America Corporation');
INSERT INTO company VALUES(317,'A-Max');
INSERT INTO company VALUES(318,'Epoch Co., Ltd.');
INSERT INTO company VALUES(319,'Supersonic Software Ltd.');
INSERT INTO company VALUES(320,'Konami Corporation');
INSERT INTO company VALUES(321,'Nissho Iwai Infocom Systems Co., Ltd.');
INSERT INTO company VALUES(322,'Looking Glass Technologies, Inc.');
INSERT INTO company VALUES(323,'EA Studios');
INSERT INTO company VALUES(324,'DTMC, Inc.');
INSERT INTO company VALUES(325,'Make Software, Inc.');
INSERT INTO company VALUES(326,'Sterling Silver Software');
INSERT INTO company VALUES(327,'KOEI Co., Ltd.');
INSERT INTO company VALUES(328,'Koei Tecmo Games Co., Ltd.');
INSERT INTO company VALUES(329,'Tecmo Koei America Corp.');
INSERT INTO company VALUES(330,'Assembly Line, The');
INSERT INTO company VALUES(331,'Empire Software');
INSERT INTO company VALUES(332,'Microsoft Corporation');
INSERT INTO company VALUES(333,'Lucasfilm Games LLC');
INSERT INTO company VALUES(334,'Enigma Variations Ltd.');
INSERT INTO company VALUES(335,'Mediagenic');
INSERT INTO company VALUES(336,'Hot-B Co., Ltd.');
INSERT INTO company VALUES(337,'Brother Industries, Ltd.');
INSERT INTO company VALUES(338,'Probe Entertainment Ltd.');
INSERT INTO company VALUES(339,'Majesco Entertainment Company');
INSERT INTO company VALUES(340,'Throwback Entertainment Inc.');
INSERT INTO company VALUES(341,'Rebellion Developments Ltd.');
INSERT INTO company VALUES(342,'ADK Corporation');
INSERT INTO company VALUES(343,'TAKARA U.S.A. CORP.');
INSERT INTO company VALUES(344,'Saurus Co., Ltd.');
INSERT INTO company VALUES(345,'Extreme Entertainment Group, Inc.');
INSERT INTO company VALUES(346,'Bit Managers S.L.');
INSERT INTO company VALUES(347,'Infogrames France S.A.S.');
INSERT INTO company VALUES(348,'Magical Company Ltd.');
INSERT INTO company VALUES(349,'Flying Tiger Entertainment, Inc.');
INSERT INTO company VALUES(350,'New World Computing, Inc.');
INSERT INTO company VALUES(351,'Ziggurat Interactive, Inc.');
INSERT INTO company VALUES(352,'G-mode Co., Ltd.');
INSERT INTO company VALUES(353,'Motivetime Ltd.');
INSERT INTO company VALUES(354,'612 Entertainment LLC.');
INSERT INTO company VALUES(355,'Taito America Corporation');
INSERT INTO company VALUES(356,'Jaleco Ltd.');
INSERT INTO company VALUES(357,'SETA Corporation');
INSERT INTO company VALUES(358,'SETA U.S.A., Inc.');
INSERT INTO company VALUES(359,'Namco Hometek Inc.');
INSERT INTO company VALUES(360,'Sunsoft');
INSERT INTO company VALUES(361,'Ratalaika Games S.L.');
INSERT INTO company VALUES(362,'T&E Soft of America, Inc.');
INSERT INTO company VALUES(363,'Starfish Inc.');
INSERT INTO company VALUES(364,'HOT-B USA, Inc.');
INSERT INTO company VALUES(365,'Malibu Interactive');
INSERT INTO company VALUES(366,'High Score Entertainment');
INSERT INTO company VALUES(367,'Polygames');
INSERT INTO company VALUES(368,'FCI');
INSERT INTO company VALUES(369,'StarCraft, Inc.');
INSERT INTO company VALUES(370,'Sir-tech Software, Inc.');
INSERT INTO company VALUES(371,'BANDAI NAMCO Games Inc.');
INSERT INTO company VALUES(372,'BANDAI NAMCO Games America Inc.');
INSERT INTO company VALUES(373,'Namco Bandai Games Inc.');
INSERT INTO company VALUES(374,'Namco Bandai Games America Inc.');
INSERT INTO company VALUES(375,'The Global Team');
INSERT INTO company VALUES(376,'Ancient Co. Ltd.');
INSERT INTO company VALUES(377,'Realtime Associates, Inc.');
INSERT INTO company VALUES(378,'Manley & Associates, Inc.');
INSERT INTO company VALUES(379,'Spectrum Holobyte, Inc.');
INSERT INTO company VALUES(380,'Yojigen');
INSERT INTO company VALUES(381,'Metro3D, Inc.');
INSERT INTO company VALUES(382,'Gaijinworks');
INSERT INTO company VALUES(383,'Metro3D Japan, Inc.');
INSERT INTO company VALUES(384,'Namco Europe Limited');
INSERT INTO company VALUES(385,'Namco Bandai Games Europe SAS');
INSERT INTO company VALUES(386,'BANDAI NAMCO Entertainment America Inc.');
INSERT INTO company VALUES(387,'Unbalance Corporation');
INSERT INTO company VALUES(388,'Gradiente Entertainment Ltda.');
INSERT INTO company VALUES(389,'Eurocom Developments Ltd');
INSERT INTO company VALUES(390,'Ignition Entertainment Ltd.');
INSERT INTO company VALUES(391,'Ignition Entertainment Ltd. USA');
INSERT INTO company VALUES(392,'ORIGIN Systems, Inc.');
INSERT INTO company VALUES(393,'GameTap LLC');
INSERT INTO company VALUES(394,'Atreid Concept SA');
INSERT INTO company VALUES(395,'Atari Games Corporation');
INSERT INTO company VALUES(396,'Tengen Ltd.');
INSERT INTO company VALUES(397,'System 3 Software Limited');
INSERT INTO company VALUES(398,'System 3 Software Ltd.');
INSERT INTO company VALUES(399,'HAL America Inc.');
INSERT INTO company VALUES(400,'City Connection Co., Ltd.');
INSERT INTO company VALUES(401,'Heart Beat');
INSERT INTO company VALUES(402,'Sting, Inc.');
INSERT INTO company VALUES(403,'Red Rat Software Ltd');
INSERT INTO company VALUES(404,'Gray Matter Inc.');
INSERT INTO company VALUES(405,'Chris Gray Enterprises Inc.');
INSERT INTO company VALUES(406,'Altron Corporation');
INSERT INTO company VALUES(407,'MindSpan');
INSERT INTO company VALUES(408,'Media Safari');
INSERT INTO company VALUES(409,'Electro Brain Corp.');
INSERT INTO company VALUES(410,'Opus Corp.');
INSERT INTO company VALUES(411,'International Computer Entertainment Ltd.');
INSERT INTO company VALUES(412,'Songbird Productions');
INSERT INTO company VALUES(413,'Kemco U.S.A., Inc.');
INSERT INTO company VALUES(414,'Atari Interactive, Inc.');
INSERT INTO company VALUES(415,'Bitmap Brothers, The');
INSERT INTO company VALUES(416,'R-Comp Interactive');
INSERT INTO company VALUES(417,'Mastertronic Group Ltd.');
INSERT INTO company VALUES(418,'WarnerActive');
INSERT INTO company VALUES(419,'AtariAge');
INSERT INTO company VALUES(420,'Glu Mobile Ltd.');
INSERT INTO company VALUES(421,'Renegade Software');
INSERT INTO company VALUES(422,'Mitchell Corporation');
INSERT INTO company VALUES(423,'Midway Mfg. Co.');
INSERT INTO company VALUES(424,'General Computer Corporation');
INSERT INTO company VALUES(425,'Atari, Inc.');
INSERT INTO company VALUES(426,'Namco Mobile');
INSERT INTO company VALUES(427,'Thunder Mountain');
INSERT INTO company VALUES(428,'Atarisoft');
INSERT INTO company VALUES(429,'THQ International Ltd.');
INSERT INTO company VALUES(430,'Namco Networks America Inc.');
INSERT INTO company VALUES(431,'Atlus U.S.A., Inc.');
INSERT INTO company VALUES(432,'Hi-Tech Expressions, Inc.');
INSERT INTO company VALUES(433,'Images Software Ltd.');
INSERT INTO company VALUES(434,'Telstar Fun and Games');
INSERT INTO company VALUES(435,'Ironwind Software');
INSERT INTO company VALUES(436,'Vap Inc.');
INSERT INTO company VALUES(437,'NTV International Corporation');
INSERT INTO company VALUES(438,'Armor Project');
INSERT INTO company VALUES(439,'Matrix Software');
INSERT INTO company VALUES(440,'Enix America Inc.');
INSERT INTO company VALUES(441,'New Frontier');
INSERT INTO company VALUES(442,'Crucial Entertainment Limited');
INSERT INTO company VALUES(443,'Accolade Europe Ltd.');
INSERT INTO company VALUES(444,'PCM Complete');
INSERT INTO company VALUES(445,'Game Freak, Inc.');
INSERT INTO company VALUES(446,'System Sacom');
INSERT INTO company VALUES(447,'AIM');
INSERT INTO company VALUES(448,'Tokuma Shoten Publishing Co., Ltd.');
INSERT INTO company VALUES(449,'Nihon Falcom Corp.');
INSERT INTO company VALUES(450,'Renovation Products, Inc.');
INSERT INTO company VALUES(451,'American Sammy Corporation');
INSERT INTO company VALUES(452,'NEC Technologies, Inc.');
INSERT INTO company VALUES(453,'Telenet Japan Co., Ltd.');
INSERT INTO company VALUES(454,'Midway Games, Inc.');
INSERT INTO company VALUES(455,'JAKKS Pacific, Inc');
INSERT INTO company VALUES(456,'Absolute Entertainment, Inc.');
INSERT INTO company VALUES(457,'Leland Corporation');
INSERT INTO company VALUES(458,'Virgin Mastertronic Ltd.');
INSERT INTO company VALUES(459,'Tronix');
INSERT INTO company VALUES(460,'Vectordean Ltd.');
INSERT INTO company VALUES(461,'Eclipse Productions');
INSERT INTO company VALUES(462,'Play It Ltd.');
INSERT INTO company VALUES(463,'Valcon Games LLC');
INSERT INTO company VALUES(464,'American Softworks Corporation');
INSERT INTO company VALUES(465,'Millennium Interactive Ltd.');
INSERT INTO company VALUES(466,'DE Act Team');
INSERT INTO company VALUES(467,'Almanic Corp.');
INSERT INTO company VALUES(468,'Paragon Publishing');
INSERT INTO company VALUES(469,'SoftKey International, Inc.');
INSERT INTO company VALUES(470,'Micomsoft');
INSERT INTO company VALUES(471,'Taito (Europe) Corporation Limited');
INSERT INTO company VALUES(472,'ICOM Simulations, Inc.');
INSERT INTO company VALUES(473,'Imagineering Inc.');
INSERT INTO company VALUES(474,'KAZe Co., Ltd.');
INSERT INTO company VALUES(475,'American Technos Inc.');
INSERT INTO company VALUES(476,'Meldac of Japan');
INSERT INTO company VALUES(477,'Genki Co., Ltd.');
INSERT INTO company VALUES(478,'Cybersoft, Inc.');
INSERT INTO company VALUES(479,'GameTek UK Ltd.');
INSERT INTO company VALUES(480,'GameTek Deutschland GmbH');
INSERT INTO company VALUES(481,'Varie Corporation');
INSERT INTO company VALUES(482,'Crosstalk Inc.');
INSERT INTO company VALUES(483,'NEC Home Electronics, Ltd.');
INSERT INTO company VALUES(484,'Atlus Osaka Development Office');
INSERT INTO company VALUES(485,'ZIOSoft, Inc.');
INSERT INTO company VALUES(486,'Pallas');
INSERT INTO company VALUES(487,'SNK Corporation of America');
INSERT INTO company VALUES(488,'K. Amusement Leasing Co.');
INSERT INTO company VALUES(489,'Axes Art Amuse');
INSERT INTO company VALUES(490,'Hect Co. Ltd.');
INSERT INTO company VALUES(491,'Anco Software Ltd.');
INSERT INTO company VALUES(492,'Vic Tokai Europe Ltd.');
INSERT INTO company VALUES(493,'Alpha Denshi Kōgyō Co., Ltd.');
INSERT INTO company VALUES(494,'SNK Playmore USA Corp.');
INSERT INTO company VALUES(495,'Radical Entertainment Inc.');
INSERT INTO company VALUES(496,'Ocean of America, Inc.');
INSERT INTO company VALUES(497,'Capcom U.S.A., Inc.');
INSERT INTO company VALUES(498,'Bitmasters, Inc.');
INSERT INTO company VALUES(499,'Acer TWP Corp');
INSERT INTO company VALUES(500,'Twilight');
INSERT INTO company VALUES(501,'Dini & Dini Productions');
INSERT INTO company VALUES(502,'Hookstone Ltd.');
INSERT INTO company VALUES(503,'MediaQuest');
INSERT INTO company VALUES(504,'Vic Tokai Corporation');
INSERT INTO company VALUES(505,'Panasonic Interactive Media');
INSERT INTO company VALUES(506,'Back Alley Publishing');
INSERT INTO company VALUES(507,'Equilibrium, Inc.');
INSERT INTO company VALUES(508,'Micronet Co. Ltd.');
INSERT INTO company VALUES(509,'Arcade Zone Ltd.');
INSERT INTO company VALUES(510,'Empire Interactive Europe Ltd.');
INSERT INTO company VALUES(511,'Alexandria, Inc.');
INSERT INTO company VALUES(512,'Sony Interactive Entertainment Inc.');
INSERT INTO company VALUES(513,'Team17 Software Limited');
INSERT INTO company VALUES(514,'Team17 Digital Limited');
INSERT INTO company VALUES(515,'I''Max Corp.');
INSERT INTO company VALUES(516,'GT Interactive Software Corp.');
INSERT INTO company VALUES(517,'Infogrames Entertainment SA');
INSERT INTO company VALUES(518,'Camerica Limited Inc.');
INSERT INTO company VALUES(519,'Virgin Studios London');
INSERT INTO company VALUES(520,'Disney Interactive (Europe, Middle East & Africa) S.A.');
INSERT INTO company VALUES(521,'Motion Pixel');
INSERT INTO company VALUES(522,'Loriciels');
INSERT INTO company VALUES(523,'Loriciel SA');
INSERT INTO company VALUES(524,'Futura');
INSERT INTO company VALUES(525,'Proein S.L.');
INSERT INTO company VALUES(526,'Samsung Electronics Co., Ltd.');
INSERT INTO company VALUES(527,'Micro World');
INSERT INTO company VALUES(528,'Electro Brain Corp. Japan');
INSERT INTO company VALUES(529,'ITL Co., Ltd.');
INSERT INTO company VALUES(530,'Digital Illusions HB');
INSERT INTO company VALUES(531,'Game Park');
INSERT INTO company VALUES(532,'21st Century Entertainment Ltd.');
INSERT INTO company VALUES(533,'Cowboy Rodeo Oy');
INSERT INTO company VALUES(534,'Strictly Limited Games');
INSERT INTO company VALUES(535,'Tantalus Interactive Pty. Ltd.');
INSERT INTO company VALUES(536,'Hasbro Japan Ltd.');
INSERT INTO company VALUES(537,'Parker Brothers International Inc.');
INSERT INTO company VALUES(538,'Parker Brothers');
INSERT INTO company VALUES(539,'Tomy Company, Ltd.');
INSERT INTO company VALUES(540,'KID Corp.');
INSERT INTO company VALUES(541,'Athena Co., Ltd.');
INSERT INTO company VALUES(542,'Arc Developments Limited');
INSERT INTO company VALUES(543,'Blaze Entertainment Ltd.');
INSERT INTO company VALUES(544,'Funcom Oslo A/S');
INSERT INTO company VALUES(545,'Dice Co., Ltd.');
INSERT INTO company VALUES(546,'Fox Interactive, Inc.');
INSERT INTO company VALUES(547,'SNK Home Entertainment, Inc.');
INSERT INTO company VALUES(548,'Zoom, Inc.');
INSERT INTO company VALUES(549,'Acme Interactive, Inc.');
INSERT INTO company VALUES(550,'FTL Games');
INSERT INTO company VALUES(551,'Visual Concepts, Ltd.');
INSERT INTO company VALUES(552,'Bandai Namco Entertainment Europe S.A.S.');
INSERT INTO company VALUES(553,'Copya System Ltd.');
INSERT INTO company VALUES(554,'Imagitec Design Inc.');
INSERT INTO company VALUES(555,'Mirage Technologies (Multimedia) Ltd.');
INSERT INTO company VALUES(556,'16/32 Systems');
INSERT INTO company VALUES(557,'Armenica, Inc.');
INSERT INTO company VALUES(558,'MicroProse Ltd.');
INSERT INTO company VALUES(559,'Sphere, Inc.');
INSERT INTO company VALUES(560,'Inline Design');
INSERT INTO company VALUES(561,'Brutal Deluxe Software');
INSERT INTO company VALUES(562,'Kalisto');
INSERT INTO company VALUES(563,'Technosoft Co., Ltd.');
INSERT INTO company VALUES(564,'SEGA Corporation');
INSERT INTO company VALUES(565,'Toshiba-EMI Ltd.');
INSERT INTO company VALUES(566,'Westwood Associates');
INSERT INTO company VALUES(567,'ASK Kodansha Co., Ltd.');
INSERT INTO company VALUES(568,'Flair Software Ltd.');
INSERT INTO company VALUES(569,'Golden Zone');
INSERT INTO company VALUES(570,'Audiogenic Software Ltd.');
INSERT INTO company VALUES(571,'Sun L');
INSERT INTO company VALUES(572,'id Software, Inc.');
INSERT INTO company VALUES(573,'Kinesoft Development Corp.');
INSERT INTO company VALUES(574,'NEC Avenue, Ltd.');
INSERT INTO company VALUES(575,'Affect Co.,Ltd');
INSERT INTO company VALUES(576,'Foley Hi-Tech Systems');
INSERT INTO company VALUES(577,'Project Power Wheels');
INSERT INTO company VALUES(578,'Riot');
INSERT INTO company VALUES(579,'Kadokawa Shoten Publishing Co. Ltd');
INSERT INTO company VALUES(580,'Leland Interactive Media');
INSERT INTO company VALUES(581,'Condor, Inc.');
INSERT INTO company VALUES(582,'Angel');
INSERT INTO company VALUES(583,'Virtual Studio');
INSERT INTO company VALUES(584,'GAMEPLAN21');
INSERT INTO company VALUES(585,'Technos Japan Corp.');
INSERT INTO company VALUES(586,'TecMagik Entertainment Ltd.');
INSERT INTO company VALUES(587,'Bandai America, Inc.');
INSERT INTO company VALUES(588,'DotEmu SAS');
INSERT INTO company VALUES(589,'Blue Turtle');
INSERT INTO company VALUES(590,'Cyberium Multi Media B.V.');
INSERT INTO company VALUES(591,'Shimada Kikaku');
INSERT INTO company VALUES(592,'Image Works');
INSERT INTO company VALUES(593,'System Vision');
INSERT INTO company VALUES(594,'Kaneko USA, Ltd.');
INSERT INTO company VALUES(595,'SOFEL Corp.');
INSERT INTO company VALUES(596,'LJN Toys, Ltd.');
INSERT INTO company VALUES(597,'Acclaim Japan, Ltd.');
INSERT INTO company VALUES(598,'LOZC/G. Amusements Co., Ltd.');
INSERT INTO company VALUES(599,'7th Level, Inc.');
INSERT INTO company VALUES(600,'Studio 3DO');
INSERT INTO company VALUES(601,'Yanoman Corporation');
INSERT INTO company VALUES(602,'MicroLeague Interactive Software');
INSERT INTO company VALUES(603,'Stormfront Studios');
INSERT INTO company VALUES(604,'B-Factory Co., Ltd.');
INSERT INTO company VALUES(605,'QUByte Interactive Ltda.');
INSERT INTO company VALUES(606,'Western Technologies Inc.');
INSERT INTO company VALUES(607,'Synergistic Software, Inc.');
INSERT INTO company VALUES(608,'Aroma Co., Ltd.');
INSERT INTO company VALUES(609,'Painting by Numbers, Ltd.');
INSERT INTO company VALUES(610,'Novotrade Software Kft.');
INSERT INTO company VALUES(611,'Distinctive Software, Inc.');
INSERT INTO company VALUES(612,'Torus Games Pty. Ltd.');
INSERT INTO company VALUES(613,'Iguana UK');
INSERT INTO company VALUES(614,'Magifact');
INSERT INTO company VALUES(615,'Empire Interactive Entertainment');
INSERT INTO company VALUES(616,'Warner Interactive Entertainment Ltd.');
INSERT INTO company VALUES(617,'Time Warner Interactive Ltd.');
INSERT INTO company VALUES(618,'LG Electronics U.K. Ltd');
INSERT INTO company VALUES(619,'LG Electronics Inc.');
INSERT INTO company VALUES(620,'Semi Logic Entertainments, Inc.');
INSERT INTO company VALUES(621,'Dynamic Planning, Inc.');
INSERT INTO company VALUES(622,'NEW Corporation');
INSERT INTO company VALUES(623,'Trimark Interactive');
INSERT INTO company VALUES(624,'Phoenix Interactive Entertainment');
INSERT INTO company VALUES(625,'Software Toolworks, Inc., The');
INSERT INTO company VALUES(626,'Fupac');
INSERT INTO company VALUES(627,'Winds Co., Ltd.');
INSERT INTO company VALUES(628,'Turner Interactive');
INSERT INTO company VALUES(629,'612 Games');
INSERT INTO company VALUES(630,'Golem Entertainment');
INSERT INTO company VALUES(631,'Field Co Ltd');
INSERT INTO company VALUES(632,'Kaneko Co., Ltd.');
INSERT INTO company VALUES(633,'Microïds');
INSERT INTO company VALUES(634,'Culture Brain Inc.');
INSERT INTO company VALUES(635,'Spidersoft Limited');
INSERT INTO company VALUES(636,'B.I.T.S., Ltd.');
INSERT INTO company VALUES(637,'Triffix Entertainment Inc.');
INSERT INTO company VALUES(638,'Hiro Co., Ltd.');
INSERT INTO company VALUES(639,'Interprog');
INSERT INTO company VALUES(640,'Jorudan Co., Ltd.');
INSERT INTO company VALUES(641,'Xanth Software F/X, Inc.');
INSERT INTO company VALUES(642,'Junkyard');
INSERT INTO company VALUES(643,'Odysseus Software');
INSERT INTO company VALUES(644,'Zeppelin Games Limited');
INSERT INTO company VALUES(645,'Merit Studios (Europe) Limited');
INSERT INTO company VALUES(646,'UPL Co., Ltd');
INSERT INTO company VALUES(647,'Teichiku Co., Ltd.');
INSERT INTO company VALUES(648,'WJS Design');
INSERT INTO company VALUES(649,'Shin-Nihon Laser Soft Co., Ltd.');
INSERT INTO company VALUES(650,'Peninsula Gameworks');
INSERT INTO company VALUES(651,'Velocity Inc.');
INSERT INTO company VALUES(652,'Culture Brain USA, Inc.');
INSERT INTO company VALUES(653,'MA-BA Corp');
INSERT INTO company VALUES(654,'Bandai S.A.');
INSERT INTO company VALUES(655,'PF Magic');
INSERT INTO company VALUES(656,'Media Rings Corporation');
INSERT INTO company VALUES(657,'Basho House');
INSERT INTO company VALUES(658,'Simon & Schuster Interactive');
INSERT INTO company VALUES(659,'Art Data Interactive, Inc.');
INSERT INTO company VALUES(660,'Micro Star Software');
INSERT INTO company VALUES(661,'ITC, Inc.');
INSERT INTO company VALUES(662,'Dark Technologies');
INSERT INTO company VALUES(663,'Aicom Corporation');
INSERT INTO company VALUES(664,'Electronics Application Co., Ltd.');
INSERT INTO company VALUES(665,'Sammy USA Corporation');
INSERT INTO company VALUES(666,'Sammy Corporation');
INSERT INTO company VALUES(667,'Nihon Bussan Co., Ltd.');
INSERT INTO company VALUES(668,'Nova Co., Ltd.');
INSERT INTO company VALUES(669,'Häus Teknikka');
INSERT INTO company VALUES(670,'Bits Corporation');
INSERT INTO company VALUES(671,'Kuusoukagaku Corp.');
INSERT INTO company VALUES(672,'Riedel Software Productions, Inc.');
INSERT INTO company VALUES(673,'Konami of America, Inc.');
INSERT INTO company VALUES(674,'CTA Developments');
INSERT INTO company VALUES(675,'Designer Software');
INSERT INTO company VALUES(676,'WayForward Technologies, Inc.');
INSERT INTO company VALUES(677,'Advance Communication Company');
INSERT INTO company VALUES(678,'Toei Animation Co., Ltd.');
INSERT INTO company VALUES(679,'Oxford Digital Enterprises Ltd.');
INSERT INTO company VALUES(680,'Software Creations of America');
INSERT INTO company VALUES(681,'Epyx, Inc.');
INSERT INTO company VALUES(682,'Melbourne House Games Ltd.');
INSERT INTO company VALUES(683,'LJN, Inc.');
INSERT INTO company VALUES(684,'Acclaim Studios Limited');
INSERT INTO company VALUES(685,'Lankhor');
INSERT INTO company VALUES(686,'Domark Group Limited');
INSERT INTO company VALUES(687,'Virtual Playground Ltd.');
INSERT INTO company VALUES(688,'MarkSoft');
INSERT INTO company VALUES(689,'Aksys Games Localization, Inc.');
INSERT INTO company VALUES(690,'Million Co., Ltd.');
INSERT INTO company VALUES(691,'Asmik Corp. of America');
INSERT INTO company VALUES(692,'Rozner Labs Software Group');
INSERT INTO company VALUES(693,'BEC Co., Ltd.');
INSERT INTO company VALUES(694,'Banpresto Co., Ltd.');
INSERT INTO company VALUES(695,'Interbec');
INSERT INTO company VALUES(696,'Bandai UK Ltd.');
INSERT INTO company VALUES(697,'Unexpected Development');
INSERT INTO company VALUES(698,'Cream Co., Ltd.');
INSERT INTO company VALUES(699,'Jordan Information Service Co., Ltd.');
INSERT INTO company VALUES(700,'Metro Games');
INSERT INTO company VALUES(701,'IGS Corp.');
INSERT INTO company VALUES(702,'NovaLogic, Inc.');
INSERT INTO company VALUES(703,'Information Global Services, Inc.');
INSERT INTO company VALUES(704,'Information Global Service');
INSERT INTO company VALUES(705,'Cryo Interactive Entertainment');
INSERT INTO company VALUES(706,'RSP, Inc.');
INSERT INTO company VALUES(707,'Instinct Design');
INSERT INTO company VALUES(708,'Wisdom Tree, Inc.');
INSERT INTO company VALUES(709,'raya systems');
INSERT INTO company VALUES(710,'Bits Studios Ltd.');
INSERT INTO company VALUES(711,'Bonsai Entertainment, Inc.');
INSERT INTO company VALUES(712,'Tahoe Software Productions');
INSERT INTO company VALUES(713,'Incredible Technologies, Inc.');
INSERT INTO company VALUES(714,'Motown Software');
INSERT INTO company VALUES(715,'Kool Brands, LLC');
INSERT INTO company VALUES(716,'Russ, Ltd.');
INSERT INTO company VALUES(717,'Now Production Co., Ltd.');
INSERT INTO company VALUES(718,'System Supply N‑Tech');
INSERT INTO company VALUES(719,'Yutaka');
INSERT INTO company VALUES(720,'GIGA');
INSERT INTO company VALUES(721,'Technical Group Laboratory, Inc.');
INSERT INTO company VALUES(722,'Tokai Engineering');
INSERT INTO company VALUES(723,'Repa Games');
INSERT INTO company VALUES(724,'KuKo');
INSERT INTO company VALUES(725,'PSCD Games');
INSERT INTO company VALUES(726,'Lance Investments');
INSERT INTO company VALUES(727,'Radiance Software');
INSERT INTO company VALUES(728,'Ruby Party');
INSERT INTO company VALUES(729,'KAN''s Co., Ltd.');
INSERT INTO company VALUES(730,'Visit Co., Ltd.');
INSERT INTO company VALUES(731,'Pandora Box');
INSERT INTO company VALUES(732,'J-Force');
INSERT INTO company VALUES(733,'Midway Home Entertainment Europe');
INSERT INTO company VALUES(734,'Japan Art Media Co., Ltd.');
INSERT INTO company VALUES(735,'Wave Corp.');
INSERT INTO company VALUES(736,'A Wave, Inc.');
INSERT INTO company VALUES(737,'King Records Co. Ltd.');
INSERT INTO company VALUES(738,'Playsoft.co');
INSERT INTO company VALUES(739,'Sunflowers Interactive Entertainment Software GmbH');
INSERT INTO company VALUES(740,'8-Bit Productions, LLC.');
INSERT INTO company VALUES(741,'Betop');
INSERT INTO company VALUES(742,'Right Stuff Corp.');
INSERT INTO company VALUES(743,'LLC Shinyuden');
INSERT INTO company VALUES(744,'Evil 3, The');
INSERT INTO company VALUES(745,'Hewson Consultants Ltd.');
INSERT INTO company VALUES(746,'Tom Create Co., Ltd.');
INSERT INTO company VALUES(747,'Monolith Corp.');
INSERT INTO company VALUES(748,'SystemSoft');
INSERT INTO company VALUES(749,'Greeting Carts');
INSERT INTO company VALUES(750,'Retroscribe');
INSERT INTO company VALUES(751,'Second Dimension R&T, LLC');
INSERT INTO company VALUES(752,'ZOO Corporation');
INSERT INTO company VALUES(753,'Shoeisha Co., Ltd.');
INSERT INTO company VALUES(754,'WaveQuest Inc.');
INSERT INTO company VALUES(755,'Health Hero Network, Inc.');
INSERT INTO company VALUES(756,'Click Health, Inc.');
INSERT INTO company VALUES(757,'St.GIGA');
INSERT INTO company VALUES(758,'Nintendo R&D2');
INSERT INTO company VALUES(759,'KSS');
INSERT INTO company VALUES(760,'Niffler Ltd.');
INSERT INTO company VALUES(761,'Nkidu Games Inc.');
INSERT INTO company VALUES(762,'The Retro Room Games LLC');
INSERT INTO company VALUES(763,'Pixel Games UK');
INSERT INTO company VALUES(764,'Ceris Software');
INSERT INTO company VALUES(765,'Sharp Corporation');
INSERT INTO company VALUES(766,'SEGA Games Co., Ltd.');
INSERT INTO company VALUES(767,'Media Factory, Inc.');
INSERT INTO company VALUES(768,'Birthday');
INSERT INTO company VALUES(769,'Thinking Rabbit Inc.');
INSERT INTO company VALUES(770,'Arc Co., Ltd.');
INSERT INTO company VALUES(771,'Westone Co., Ltd.');
INSERT INTO company VALUES(772,'Sakata SAS Co., Ltd.');
INSERT INTO company VALUES(773,'Office Koukan');
INSERT INTO company VALUES(774,'Shouei System');
INSERT INTO company VALUES(775,'Funcom Productions A/S');
INSERT INTO company VALUES(776,'Metro Corporation');
INSERT INTO company VALUES(777,'Adrenalin Entertainment');
INSERT INTO company VALUES(778,'Agenda Co., Ltd.');
INSERT INTO company VALUES(779,'Norse');
INSERT INTO company VALUES(780,'Tan Ton Nerw Information Co., Ltd.');
INSERT INTO company VALUES(781,'SPS Co., Ltd.');
INSERT INTO company VALUES(782,'Rollogame Ltd.');
INSERT INTO company VALUES(783,'Glodia');
INSERT INTO company VALUES(784,'AlfaSystem Co., Ltd.');
INSERT INTO company VALUES(785,'Media Works Inc.');
INSERT INTO company VALUES(786,'NCM Entertainment');
INSERT INTO company VALUES(787,'Ringler Studios');
INSERT INTO company VALUES(788,'Peakstar Software');
INSERT INTO company VALUES(789,'Pax Softnica');
INSERT INTO company VALUES(790,'Max Entertainment');
INSERT INTO company VALUES(791,'XYZ Productions');
INSERT INTO company VALUES(792,'Triad Co., Ltd.');
INSERT INTO company VALUES(793,'Mega Cat Studios, Inc.');
INSERT INTO company VALUES(794,'Devolver Digital, Inc.');
INSERT INTO company VALUES(795,'Rastersoft');
INSERT INTO company VALUES(796,'Chaos89.com');
INSERT INTO company VALUES(797,'OlderGames');
INSERT INTO company VALUES(798,'MicroDeal Ltd.');
INSERT INTO company VALUES(799,'Sierra On-Line, Inc.');
INSERT INTO company VALUES(800,'Philips do Brasil Ltda.');
INSERT INTO company VALUES(801,'Games to Learn By, Inc.');
INSERT INTO company VALUES(802,'Starpath Corporation');
INSERT INTO company VALUES(803,'Misosys, Inc.');
INSERT INTO company VALUES(804,'Sega/Gremlin');
INSERT INTO company VALUES(805,'Timex Computer Corporation');
INSERT INTO company VALUES(806,'Cogito Software Company');
INSERT INTO company VALUES(807,'Infinity Co., Ltd.');
INSERT INTO company VALUES(808,'Third Stage');
INSERT INTO company VALUES(809,'Universal Co., Ltd.');
INSERT INTO company VALUES(810,'Chatnoir Co., Ltd.');
INSERT INTO company VALUES(811,'Itsui');
INSERT INTO company VALUES(812,'Alpha-Beta');
INSERT INTO company VALUES(813,'Lenar Co., Ltd.');
INSERT INTO company VALUES(814,'Banpre Kikaku Co., Ltd.');
INSERT INTO company VALUES(815,'Aspect Co., Ltd.');
INSERT INTO company VALUES(816,'Banalex');
INSERT INTO company VALUES(817,'Daft Co., Ltd.');
INSERT INTO company VALUES(818,'Sun Corporation Europe');
INSERT INTO company VALUES(819,'Paon Corporation, Ltd.');
INSERT INTO company VALUES(820,'Earthly Soft');
INSERT INTO company VALUES(821,'HappySoft');
INSERT INTO company VALUES(822,'TamTam Co., Ltd.');
INSERT INTO company VALUES(823,'Tomcat System');
INSERT INTO company VALUES(824,'GTE Vantage Inc.');
INSERT INTO company VALUES(825,'GTE Entertainment');
INSERT INTO company VALUES(826,'Nexus Interact, Ltd.');
INSERT INTO company VALUES(827,'Atelier Double Co. Ltd.');
INSERT INTO company VALUES(828,'Powwow');
INSERT INTO company VALUES(829,'extreme Co.,Ltd.');
INSERT INTO company VALUES(830,'Columbus Circle');
INSERT INTO company VALUES(831,'Spike Chunsoft Co., Ltd.');
INSERT INTO company VALUES(832,'Character Soft Co., Ltd.');
INSERT INTO company VALUES(833,'CA Production');
INSERT INTO company VALUES(834,'Amble Ltd.');
INSERT INTO company VALUES(835,'Climax Entertainment');
INSERT INTO company VALUES(836,'Humming Bird Soft');
INSERT INTO company VALUES(837,'Fill in Café Co., Ltd.');
INSERT INTO company VALUES(838,'Dempa Shimbunsha');
INSERT INTO company VALUES(839,'MonkeyPaw Games Inc.');
INSERT INTO company VALUES(840,'Polestar Co., Ltd.');
INSERT INTO company VALUES(841,'Terajima Joho Kikaku Co., Ltd.');
INSERT INTO company VALUES(842,'Eleven Co., Ltd.');
INSERT INTO company VALUES(843,'Softgarage');
INSERT INTO company VALUES(844,'Sigma Enterprises, Inc.');
INSERT INTO company VALUES(845,'GungHo Online Entertainment, Inc.');
INSERT INTO company VALUES(846,'Domark Software, Inc.');
INSERT INTO company VALUES(847,'Cartoon Mavericks, The');
INSERT INTO company VALUES(848,'Office I');
INSERT INTO company VALUES(849,'Davidson & Associates, Inc.');
INSERT INTO company VALUES(850,'Jordan Freeman Group, LLC');
INSERT INTO company VALUES(851,'Jumpstart Games, Inc.');
INSERT INTO company VALUES(852,'PortableDev');
INSERT INTO company VALUES(853,'CollectorVision Games Inc.');
INSERT INTO company VALUES(854,'iam8bit, Inc.');
INSERT INTO company VALUES(855,'Multimedia Intelligence Transfer Co., Ltd.');
INSERT INTO company VALUES(856,'Crea-Tech Inc.');
INSERT INTO company VALUES(857,'Enterbrain, Inc.');
INSERT INTO company VALUES(858,'Gangoo, Inc.');
INSERT INTO company VALUES(859,'Graphic Research Co., Ltd.');
INSERT INTO company VALUES(860,'CreamSoft Inc.');
INSERT INTO company VALUES(861,'Bits Laboratory');
INSERT INTO company VALUES(862,'Ajinomoto Co., Inc.');
INSERT INTO company VALUES(863,'Mindware Corp.');
INSERT INTO company VALUES(864,'Colpax');
INSERT INTO company VALUES(865,'Datasoft, Inc.');
INSERT INTO company VALUES(866,'Coleco Industries, Inc.');
INSERT INTO company VALUES(867,'Mediamuse');
INSERT INTO company VALUES(868,'NuFX, Inc.');
INSERT INTO company VALUES(869,'Tandem Verlag GmbH');
INSERT INTO company VALUES(870,'Nichibutsu');
INSERT INTO company VALUES(871,'Super Fighter Team');
INSERT INTO company VALUES(872,'Tecmo Koei Games Co., Ltd.');
INSERT INTO company VALUES(873,'Romstar, Inc.');
INSERT INTO company VALUES(874,'Access co., ltd.');
INSERT INTO company VALUES(875,'Tao Human Systems Co,. Ltd.');
INSERT INTO company VALUES(876,'Scenario Developments');
INSERT INTO company VALUES(877,'Santa Claus');
INSERT INTO company VALUES(878,'RetroSouls');
INSERT INTO company VALUES(879,'Tsukuda Original Co.,Ltd.');
INSERT INTO company VALUES(880,'KIDZ Health Software, Inc.');
INSERT INTO company VALUES(881,'Halestorm, Inc.');
INSERT INTO company VALUES(882,'Able Corporation');
INSERT INTO company VALUES(883,'Gainax Co., Ltd.');
INSERT INTO company VALUES(884,'Bothtec, Inc.');
INSERT INTO company VALUES(885,'NEC Interchannel, Ltd.');
INSERT INTO company VALUES(886,'Seibu Kaihatsu Inc.');
INSERT INTO company VALUES(887,'FabTek, Inc.');
INSERT INTO company VALUES(888,'Bignet U.S.A., Inc.');
INSERT INTO company VALUES(889,'Rumic Soft');
INSERT INTO company VALUES(890,'64WD Creation S.A.R.L.');
INSERT INTO company VALUES(891,'Left Field Entertainment');
INSERT INTO company VALUES(892,'Rainbow Arts Software GmbH');
INSERT INTO company VALUES(893,'KOEI Korea Corporation');
INSERT INTO company VALUES(894,'Plex');
INSERT INTO company VALUES(895,'Acer Third Wave Software (Beijing) Co., Ltd');
INSERT INTO company VALUES(896,'Production I.G, Inc.');
INSERT INTO company VALUES(897,'Chickenhead');
INSERT INTO company VALUES(898,'Play Avenue');
INSERT INTO company VALUES(899,'TNN');
INSERT INTO company VALUES(900,'Be-On Works');
INSERT INTO company VALUES(901,'Outrigger Koubou');
INSERT INTO company VALUES(902,'Fujicom Co. Ltd');
INSERT INTO company VALUES(903,'Levande Böcker i Norden AB');
INSERT INTO company VALUES(904,'Mitsui Fudosan Co., Ltd.');
INSERT INTO company VALUES(905,'Micronics');
INSERT INTO company VALUES(906,'Argonaut Games PLC');
INSERT INTO company VALUES(907,'OLM Digital, Inc.');
INSERT INTO company VALUES(908,'Culture Brain Excel Inc.');
INSERT INTO company VALUES(909,'Raizing Co., Ltd.');
INSERT INTO company VALUES(910,'Illusions Gaming Company, The');
INSERT INTO company VALUES(911,'Dragnet Incorporated');
INSERT INTO company VALUES(912,'Visco Corporation');
INSERT INTO company VALUES(913,'Geo Factory Co.,Ltd.');
INSERT INTO company VALUES(914,'Opera House Inc.');
INSERT INTO company VALUES(915,'Yonezawa PR21');
INSERT INTO company VALUES(916,'Graffiti');
INSERT INTO company VALUES(917,'Givro');
INSERT INTO company VALUES(918,'Summer Project');
INSERT INTO company VALUES(919,'Communication Group Plum');
INSERT INTO company VALUES(920,'indieszero Co., Ltd.');
INSERT INTO company VALUES(921,'Game Arts Co., Ltd.');
INSERT INTO company VALUES(922,'Argent');
INSERT INTO company VALUES(923,'Khaos');
INSERT INTO company VALUES(924,'GAPS Inc.');
INSERT INTO company VALUES(925,'Studio Saizensen Ltd.');
INSERT INTO company VALUES(926,'Degica Co., Ltd.');
INSERT INTO company VALUES(927,'Foxbat');
INSERT INTO company VALUES(928,'Tommo Inc.');
INSERT INTO company VALUES(929,'Blazepro Technology Company');
INSERT INTO company VALUES(930,'Mojon Twins, The');
INSERT INTO company VALUES(931,'Ubhres Productions');
INSERT INTO company VALUES(932,'1985 Alternativo');
INSERT INTO company VALUES(933,'G is for Game');
INSERT INTO company VALUES(934,'Purples Studio');
INSERT INTO company VALUES(935,'RGCD.DEV Ltd');
INSERT INTO company VALUES(936,'Natsu System');
INSERT INTO company VALUES(937,'Advanced Productions, Inc.');
INSERT INTO company VALUES(938,'Digital Eclipse Software, Inc.');
INSERT INTO company VALUES(939,'Midway Games Limited');
INSERT INTO company VALUES(940,'Tiger Electronics, Inc.');
INSERT INTO company VALUES(941,'Matt Hughson Games');
INSERT INTO company VALUES(942,'Limited Run Games, Inc.');
INSERT INTO company VALUES(943,'Gamepot Inc.');
INSERT INTO company VALUES(944,'Night Dive Studios, LLC');
INSERT INTO company VALUES(945,'Dentons');
INSERT INTO company VALUES(946,'Micro Cabin Corp.');
INSERT INTO company VALUES(947,'Bitmap Bureau Ltd.');
INSERT INTO company VALUES(948,'Eastasiasoft Limited');
INSERT INTO company VALUES(949,'Home Data Corp.');
INSERT INTO company VALUES(950,'Nippon Bcom Co., Ltd.');
INSERT INTO company VALUES(951,'ISCO, Inc.');
INSERT INTO company VALUES(952,'WiZ');
INSERT INTO company VALUES(953,'CBS Electronics');
INSERT INTO company VALUES(954,'Stambouli Frères S.A.');
INSERT INTO company VALUES(955,'Nintendo Leisure System');
INSERT INTO company VALUES(956,'Westside Soft House');
INSERT INTO company VALUES(957,'Nintendo of Canada Ltd.');
INSERT INTO company VALUES(958,'Melbourne House Software (Australia) Pty. Ltd.');
INSERT INTO company VALUES(959,'Melbourne House');
INSERT INTO company VALUES(960,'Soft Pro International');
INSERT INTO company VALUES(961,'Digital Controls, Inc.');
INSERT INTO company VALUES(962,'Universe');
INSERT INTO company VALUES(963,'Ariolasoft UK');
INSERT INTO company VALUES(964,'Living Mobile GmbH');
INSERT INTO company VALUES(965,'Tozai, Inc.');
INSERT INTO company VALUES(966,'Sony Corporation');
INSERT INTO company VALUES(967,'Software Projects Ltd.');
INSERT INTO company VALUES(968,'Petaco S.A.');
INSERT INTO company VALUES(969,'Bug-Byte Software Ltd.');
INSERT INTO company VALUES(970,'Commodore Business Machines (UK) Ltd.');
INSERT INTO company VALUES(971,'Gradiente Industrial S.A.');
INSERT INTO company VALUES(972,'Microbyte');
INSERT INTO company VALUES(973,'Philips Export B.V.');
INSERT INTO company VALUES(974,'Commodore Japan Limited');
INSERT INTO company VALUES(975,'Polyvox');
INSERT INTO company VALUES(976,'ME-TA Elektronik Endüstri ve Ticaret A.Ş.');
INSERT INTO company VALUES(977,'Americana Software Limited');
INSERT INTO company VALUES(978,'Zemina Co.');
INSERT INTO company VALUES(979,'Bally Midway Mfg Co.');
INSERT INTO company VALUES(980,'Kawa Denshi Giken K.K.');
INSERT INTO company VALUES(981,'Eaglesoft');
INSERT INTO company VALUES(982,'Vifi Anaya');
INSERT INTO company VALUES(983,'Bandai Namco Studios Inc.');
INSERT INTO company VALUES(984,'Sord Computer Corporation');
INSERT INTO company VALUES(985,'Nippon Dexter Co., Ltd.');
INSERT INTO company VALUES(986,'Williams Electronics, Inc.');
INSERT INTO company VALUES(987,'Iwasaki Electronics Co. Ltd.');
INSERT INTO company VALUES(988,'Sears, Roebuck and Co.');
INSERT INTO company VALUES(989,'Universe Affiliated International, Inc.');
INSERT INTO company VALUES(990,'Sidam');
INSERT INTO company VALUES(991,'Inversiones Recreativas, S. A.');
INSERT INTO company VALUES(992,'Nichibutsu U.K., Ltd.');
INSERT INTO company VALUES(993,'SEGA Enterprises, Inc.');
INSERT INTO company VALUES(994,'British Sky Broadcasting Ltd.');
INSERT INTO company VALUES(995,'Nidecom Soft');
INSERT INTO company VALUES(996,'Coleco Holdings LLC');
INSERT INTO company VALUES(997,'Casio Computer Co., Ltd.');
INSERT INTO company VALUES(998,'Electric Software Limited');
INSERT INTO company VALUES(999,'INTV Corp.');
INSERT INTO company VALUES(1000,'dB-SOFT');
INSERT INTO company VALUES(1001,'NetFarm Communications, Inc.');
INSERT INTO company VALUES(1002,'Home Entertainment Suppliers Pty. Ltd.');
INSERT INTO company VALUES(1003,'Philips Ibérica S.A.E.');
INSERT INTO company VALUES(1004,'Tehkan Ltd.');
INSERT INTO company VALUES(1005,'Video Ware, Inc.');
INSERT INTO company VALUES(1006,'Quicksilva Ltd.');
INSERT INTO company VALUES(1007,'CGE Services Corporation');
INSERT INTO company VALUES(1008,'Mass Tael Co., Ltd.');
INSERT INTO company VALUES(1009,'Spectravideo International Ltd.');
INSERT INTO company VALUES(1010,'Random House Co., Ltd.');
INSERT INTO company VALUES(1011,'Nintendo R&D4');
INSERT INTO company VALUES(1012,'Systems Research & Development Co., Ltd.');
INSERT INTO company VALUES(1013,'Nihon Micom Kaihatsu');
INSERT INTO company VALUES(1014,'Imagine');
INSERT INTO company VALUES(1015,'Imagine Software Ltd.');
INSERT INTO company VALUES(1016,'Grandslam Entertainments Ltd.');
INSERT INTO company VALUES(1017,'Bear''s Corporation');
INSERT INTO company VALUES(1018,'Interceptor Micro''s');
INSERT INTO company VALUES(1019,'Texas Instruments Incorporated');
INSERT INTO company VALUES(1020,'Mattel Electronics');
INSERT INTO company VALUES(1021,'Beiks LLC');
INSERT INTO company VALUES(1022,'Brøderbund Japan Inc.');
INSERT INTO company VALUES(1023,'Dro Soft');
INSERT INTO company VALUES(1024,'Karateka, LLC');
INSERT INTO company VALUES(1025,'Pony, Inc.');
INSERT INTO company VALUES(1026,'Ponyca');
INSERT INTO company VALUES(1027,'Micro Graphic Image');
INSERT INTO company VALUES(1028,'Zafiro');
INSERT INTO company VALUES(1029,'Synapse Software Corporation');
INSERT INTO company VALUES(1030,'Synsoft');
INSERT INTO company VALUES(1031,'Showcase Software');
INSERT INTO company VALUES(1032,'Hudson Soft Ltd.');
INSERT INTO company VALUES(1033,'Kuma Computers Ltd.');
INSERT INTO company VALUES(1034,'Denyusya Square Co., Ltd.');
INSERT INTO company VALUES(1035,'Memetron');
INSERT INTO company VALUES(1036,'Technopolis Soft');
INSERT INTO company VALUES(1037,'NEXOFT Corporation');
INSERT INTO company VALUES(1038,'GAME STUDIO Inc.');
INSERT INTO company VALUES(1039,'Centuri, Inc.');
INSERT INTO company VALUES(1040,'Crux');
INSERT INTO company VALUES(1041,'Carry Lab');
INSERT INTO company VALUES(1042,'Koei Tecmo America Corp.');
INSERT INTO company VALUES(1043,'Tecmo Koei Europe Ltd.');
INSERT INTO company VALUES(1044,'Konami Ltd.');
INSERT INTO company VALUES(1045,'First Star Software, Inc.');
INSERT INTO company VALUES(1046,'Hi-Tec Software Ltd.');
INSERT INTO company VALUES(1047,'Tynesoft Computer Software');
INSERT INTO company VALUES(1048,'Beyond');
INSERT INTO company VALUES(1049,'Wicked Software');
INSERT INTO company VALUES(1050,'Taxan USA Corp.');
INSERT INTO company VALUES(1051,'Micro Academy');
INSERT INTO company VALUES(1052,'Taiyo System Co., Ltd.');
INSERT INTO company VALUES(1053,'Creative Software, Inc.');
INSERT INTO company VALUES(1054,'TO TEK International');
INSERT INTO company VALUES(1055,'Apollo Technica');
INSERT INTO company VALUES(1056,'Audiogenic Ltd.');
INSERT INTO company VALUES(1057,'Salio, Inc.');
INSERT INTO company VALUES(1058,'KitKorp, Inc');
INSERT INTO company VALUES(1059,'Royal Kougyou');
INSERT INTO company VALUES(1060,'Tandy Corporation');
INSERT INTO company VALUES(1061,'Marionette Co., Ltd.');
INSERT INTO company VALUES(1062,'Proein S.A.');
INSERT INTO company VALUES(1063,'Mastertronic Ltd.');
INSERT INTO company VALUES(1064,'G1M2');
INSERT INTO company VALUES(1065,'Kawada Co., Ltd.');
INSERT INTO company VALUES(1066,'TRY Co., Ltd.');
INSERT INTO company VALUES(1067,'Revolutionary Concepts');
INSERT INTO company VALUES(1068,'Encore');
INSERT INTO company VALUES(1069,'Fuji Television Network, Inc.');
INSERT INTO company VALUES(1070,'D4Enterprise Co., Ltd.');
INSERT INTO company VALUES(1071,'Toaplan Co., Ltd.');
INSERT INTO company VALUES(1072,'Plaion GmbH (Austria)');
INSERT INTO company VALUES(1073,'Bitwave AB');
INSERT INTO company VALUES(1074,'TAKARATOMY');
INSERT INTO company VALUES(1075,'Use Corporation');
INSERT INTO company VALUES(1076,'Towa Chiki');
INSERT INTO company VALUES(1077,'Disk Original Group');
INSERT INTO company VALUES(1078,'Scap Trust');
INSERT INTO company VALUES(1079,'CBS/Sony Group Inc.');
INSERT INTO company VALUES(1080,'Taito Software Inc.');
INSERT INTO company VALUES(1081,'France Image Logiciel');
INSERT INTO company VALUES(1082,'Discovery Software International, Inc.');
INSERT INTO company VALUES(1083,'Imagine Co., Ltd.');
INSERT INTO company VALUES(1084,'Grandstand Leisure Ltd');
INSERT INTO company VALUES(1085,'Hacker International');
INSERT INTO company VALUES(1086,'Another Ltd.');
INSERT INTO company VALUES(1087,'Rix Soft');
INSERT INTO company VALUES(1088,'Musical Plan Ltd.');
INSERT INTO company VALUES(1089,'American Action AB');
INSERT INTO company VALUES(1090,'Toho Cinefile-Soft Library');
INSERT INTO company VALUES(1091,'Sedic');
INSERT INTO company VALUES(1092,'Databyte');
INSERT INTO company VALUES(1093,'Action Graphics, Inc.');
INSERT INTO company VALUES(1094,'Rushware GmbH');
INSERT INTO company VALUES(1095,'Commodore Gaming');
INSERT INTO company VALUES(1096,'Edge Computers Ltd.');
INSERT INTO company VALUES(1097,'WorkJam Co., Ltd.');
INSERT INTO company VALUES(1098,'Sonata');
INSERT INTO company VALUES(1099,'Softvision Co., Ltd.');
INSERT INTO company VALUES(1100,'East Cube');
INSERT INTO company VALUES(1101,'Scorpion Software');
INSERT INTO company VALUES(1102,'Wood Place Inc.');
INSERT INTO company VALUES(1103,'Login Soft');
INSERT INTO company VALUES(1104,'Hi-Score Media Work Corp.');
INSERT INTO company VALUES(1105,'NEC Home Electronics (U.S.A.) Inc.');
INSERT INTO company VALUES(1106,'Gakken Co., Ltd.');
INSERT INTO company VALUES(1107,'Animation 20 Co., Ltd.');
INSERT INTO company VALUES(1108,'Bergsala AB');
INSERT INTO company VALUES(1109,'Edia Co.,Ltd.');
INSERT INTO company VALUES(1110,'Shockwave');
INSERT INTO company VALUES(1111,'Handmark, Inc.');
INSERT INTO company VALUES(1112,'Atlus Mobile Co., Ltd.');
INSERT INTO company VALUES(1113,'Vid Kidz');
INSERT INTO company VALUES(1114,'Entex Industries, Inc.');
INSERT INTO company VALUES(1115,'TOPICS Entertainment, Inc.');
INSERT INTO company VALUES(1116,'Xtalsoft Co., Ltd.');
INSERT INTO company VALUES(1117,'All American Adventures');
INSERT INTO company VALUES(1118,'Ediciel Matra et Hachette');
INSERT INTO company VALUES(1119,'MiCROViSion Inc.');
INSERT INTO company VALUES(1120,'Apros');
INSERT INTO company VALUES(1121,'Kogado Studio, Inc.');
INSERT INTO company VALUES(1122,'Kogado Software Products');
INSERT INTO company VALUES(1123,'Kemco');
INSERT INTO company VALUES(1124,'Artec Corp.');
INSERT INTO company VALUES(1125,'Ving Co., Ltd.');
INSERT INTO company VALUES(1126,'Mobirix Corporation');
INSERT INTO company VALUES(1127,'Soft-World International Corporation');
INSERT INTO company VALUES(1128,'Kaasa Solution GmbH');
INSERT INTO company VALUES(1129,'Firebird Software');
INSERT INTO company VALUES(1130,'Backbone Entertainment, Inc.');
INSERT INTO company VALUES(1131,'Midway Amusement Games, LLC');
INSERT INTO company VALUES(1132,'Shadowsoft');
INSERT INTO company VALUES(1133,'Sanritsu Denki Co., Ltd.');
INSERT INTO company VALUES(1134,'Escape');
INSERT INTO company VALUES(1135,'Piccari Games');
INSERT INTO company VALUES(1136,'Andrew Greenberg, Inc.');
INSERT INTO company VALUES(1137,'Robert Woodhead, Inc.');
INSERT INTO company VALUES(1138,'Newtopia Planning');
INSERT INTO company VALUES(1139,'Scitron & Art Inc.');
INSERT INTO company VALUES(1140,'MGP');
INSERT INTO company VALUES(1141,'Hyperware');
INSERT INTO company VALUES(1142,'Topo Soft');
INSERT INTO company VALUES(1143,'GO! Media Holdings Ltd.');
INSERT INTO company VALUES(1144,'Live Planning');
INSERT INTO company VALUES(1145,'Dual Corporation');
INSERT INTO company VALUES(1146,'Merlin Software');
INSERT INTO company VALUES(1147,'Lucasfilm Ltd. LLC');
INSERT INTO company VALUES(1148,'Mr. Micro Ltd.');
INSERT INTO company VALUES(1149,'Klon');
INSERT INTO company VALUES(1150,'Mentrix Software, Inc.');
INSERT INTO company VALUES(1151,'Tatsujin Co., Ltd.');
INSERT INTO company VALUES(1152,'505 Games S.R.L.');
INSERT INTO company VALUES(1153,'16-Blitz');
INSERT INTO company VALUES(1154,'Arcadia Systems, Inc.');
INSERT INTO company VALUES(1155,'World Games');
INSERT INTO company VALUES(1156,'Shinsei Kōgyō Ltd.');
INSERT INTO company VALUES(1157,'CSG Imagesoft Inc.');
INSERT INTO company VALUES(1158,'Infocom, Inc.');
INSERT INTO company VALUES(1159,'sAs Co., Ltd.');
INSERT INTO company VALUES(1160,'Tamtex');
INSERT INTO company VALUES(1161,'Soft Machine');
INSERT INTO company VALUES(1162,'Kyodai Software Marketing, Inc.');
INSERT INTO company VALUES(1163,'Fujisankei Communications International, Inc.');
INSERT INTO company VALUES(1164,'Yellow Horn Co., Ltd.');
INSERT INTO company VALUES(1165,'Ultra Software Corporation');
INSERT INTO company VALUES(1166,'Atari Games, Inc.');
INSERT INTO company VALUES(1167,'RAD Games');
INSERT INTO company VALUES(1168,'ACE');
INSERT INTO company VALUES(1169,'Induction Produce');
INSERT INTO company VALUES(1170,'Kaken Corp.');
INSERT INTO company VALUES(1171,'Kyugo Trading Co., Ltd');
INSERT INTO company VALUES(1172,'Capcom Interactive, Inc.');
INSERT INTO company VALUES(1173,'Color Dreams, Inc.');
INSERT INTO company VALUES(1174,'Joy Van');
INSERT INTO company VALUES(1175,'Sachen');
INSERT INTO company VALUES(1176,'Bit Corp');
INSERT INTO company VALUES(1177,'Sony Online Entertainment Inc.');
INSERT INTO company VALUES(1178,'Klassix');
INSERT INTO company VALUES(1179,'American Video Entertainment Inc.');
INSERT INTO company VALUES(1180,'S.E.I.');
INSERT INTO company VALUES(1181,'Milmar Indústria e Comércio Ltda.');
INSERT INTO company VALUES(1182,'Bunch Games');
INSERT INTO company VALUES(1183,'Thin Chen Enterprise');
INSERT INTO company VALUES(1184,'Domark Limited');
INSERT INTO company VALUES(1185,'Zippo Games');
INSERT INTO company VALUES(1186,'Ultra Games');
INSERT INTO company VALUES(1187,'AM R&D Dept. #2');
INSERT INTO company VALUES(1188,'D. Gottlieb & Co.');
INSERT INTO company VALUES(1189,'Sony Pictures Mobile');
INSERT INTO company VALUES(1190,'Tokyo Design Center');
INSERT INTO company VALUES(1191,'Seismic Software Inc.');
INSERT INTO company VALUES(1192,'ZAP Corporation');
INSERT INTO company VALUES(1193,'NMK Co. Ltd.');
INSERT INTO company VALUES(1194,'Milton Bradley Co.');
INSERT INTO company VALUES(1195,'Mars Corp.');
INSERT INTO company VALUES(1196,'Arc System Works Europe Ltd.');
INSERT INTO company VALUES(1197,'MFORMA Group Inc.');
INSERT INTO company VALUES(1198,'K-Byte');
INSERT INTO company VALUES(1199,'d3m');
INSERT INTO company VALUES(1200,'Sonic Powered Co., Ltd.');
INSERT INTO company VALUES(1201,'Althi Inc.');
INSERT INTO company VALUES(1202,'Mebius');
INSERT INTO company VALUES(1203,'Fonfun Corporation');
INSERT INTO company VALUES(1204,'Master Designer Software, Inc.');
INSERT INTO company VALUES(1205,'Cinemaware Corporation');
INSERT INTO company VALUES(1206,'CW Entertainment USA, LLC');
INSERT INTO company VALUES(1207,'Philips Interactive Media Systems');
INSERT INTO company VALUES(1208,'Cinemaware');
INSERT INTO company VALUES(1209,'Cinemaware, Inc.');
INSERT INTO company VALUES(1210,'CDTV Publishing');
INSERT INTO company VALUES(1211,'EDOS');
INSERT INTO company VALUES(1212,'Mirror Image');
INSERT INTO company VALUES(1213,'Aisystem Tokyo');
INSERT INTO company VALUES(1214,'Treco');
INSERT INTO company VALUES(1215,'Ninja Games Japan Co., Ltd.');
INSERT INTO company VALUES(1216,'Joyful table');
INSERT INTO company VALUES(1217,'UFO Interactive Games, Inc.');
INSERT INTO company VALUES(1218,'Infinite Ventures, Inc.');
INSERT INTO company VALUES(1219,'Cirque Verte');
INSERT INTO company VALUES(1220,'SEGA-AM2 Co., LTD.');
INSERT INTO company VALUES(1221,'Tec Toy S.A.');
INSERT INTO company VALUES(1222,'Free Fall Associates');
INSERT INTO company VALUES(1223,'EmperoR Studios');
INSERT INTO company VALUES(1224,'Team Shinobi');
INSERT INTO company VALUES(1225,'Nightdive Studios, LLC');
INSERT INTO company VALUES(1226,'Eurogold');
INSERT INTO company VALUES(1227,'Digital Integration Ltd.');
INSERT INTO company VALUES(1228,'Byte Back');
INSERT INTO company VALUES(1229,'Superior Interactive');
INSERT INTO company VALUES(1230,'BUG Multisystem Ltd.');
INSERT INTO company VALUES(1231,'Electrocoin Automatics Ltd.');
INSERT INTO company VALUES(1232,'Classic Game Publishers, Inc.');
INSERT INTO company VALUES(1233,'Micro Fun');
INSERT INTO company VALUES(1234,'Exidy, Incorporated');
INSERT INTO company VALUES(1235,'Prism Leisure Corporation Plc');
INSERT INTO company VALUES(1236,'Chillingo Ltd');
INSERT INTO company VALUES(1237,'K-Tel International (UK) Ltd');
INSERT INTO company VALUES(1238,'State Soft Ltd.');
INSERT INTO company VALUES(1239,'Aackosoft International B.V.');
INSERT INTO company VALUES(1240,'Comptiq');
INSERT INTO company VALUES(1241,'Orpheus Ltd');
INSERT INTO company VALUES(1242,'ShareData, Inc.');
INSERT INTO company VALUES(1243,'American Game Cartridges, Inc.');
INSERT INTO company VALUES(1244,'Softie, Inc.');
INSERT INTO company VALUES(1245,'Watara');
INSERT INTO company VALUES(1246,'Creative Materials');
INSERT INTO company VALUES(1247,'Odyssey Software, Inc.');
INSERT INTO company VALUES(1248,'Alternative Software Ltd.');
INSERT INTO company VALUES(1249,'Mind''s Eye Technology');
INSERT INTO company VALUES(1250,'MicroMosaics Productions, Inc.');
INSERT INTO company VALUES(1251,'Atari2600.com');
INSERT INTO company VALUES(1252,'ResQsoft Productions');
INSERT INTO company VALUES(1253,'MCM Software');
INSERT INTO company VALUES(1254,'Eastridge Technology');
INSERT INTO company VALUES(1255,'Computer & Entertainment Inc.');
INSERT INTO company VALUES(1256,'IJE, Inc.');
INSERT INTO company VALUES(1257,'PAL SOFT');
INSERT INTO company VALUES(1258,'Tad Corporation');
INSERT INTO company VALUES(1259,'Graftgold Ltd.');
INSERT INTO company VALUES(1260,'SourceNext Corporation');
INSERT INTO company VALUES(1261,'Interlink');
INSERT INTO company VALUES(1262,'Tapwave, Inc.');
INSERT INTO company VALUES(1263,'EIM Ltd.');
INSERT INTO company VALUES(1264,'Anuman Interactive SA');
INSERT INTO company VALUES(1265,'Titus Ltd.');
INSERT INTO company VALUES(1266,'Pixel');
INSERT INTO company VALUES(1267,'Ozark Softscape');
INSERT INTO company VALUES(1268,'International Business Machines Corporation (IBM)');
INSERT INTO company VALUES(1269,'Virgin Mastertronic International, Inc.');
INSERT INTO company VALUES(1270,'Milton Bradley Ltd.');
INSERT INTO company VALUES(1271,'Himax');
INSERT INTO company VALUES(1272,'Sage''s Creation, Inc.');
INSERT INTO company VALUES(1273,'Microids SA');
INSERT INTO company VALUES(1274,'Dynamix, Inc.');
INSERT INTO company VALUES(1275,'Mindscape International Japan Inc.');
INSERT INTO company VALUES(1276,'Mattel, Inc.');
INSERT INTO company VALUES(1277,'Team Murata Keikaku');
INSERT INTO company VALUES(1278,'Respray');
INSERT INTO company VALUES(1279,'Sandcastle');
INSERT INTO company VALUES(1280,'BrainGrey');
INSERT INTO company VALUES(1281,'Locomotive Co., Ltd.');
INSERT INTO company VALUES(1282,'Publishing International');
INSERT INTO company VALUES(1283,'Software Resources International');
INSERT INTO company VALUES(1284,'Meldac of America Inc.');
INSERT INTO company VALUES(1285,'Idea-Tek, Inc.');
INSERT INTO company VALUES(1286,'Super Mega');
INSERT INTO company VALUES(1287,'Active Enterprises Ltd.');
INSERT INTO company VALUES(1288,'Rare, Ltd.');
INSERT INTO company VALUES(1289,'Tradewest Games Ltd.');
INSERT INTO company VALUES(1290,'Optimus Software Ltd');
INSERT INTO company VALUES(1291,'Codemasters Software Company Limited, The');
INSERT INTO company VALUES(1292,'Firebird Licensees Inc.');
INSERT INTO company VALUES(1293,'Hybrid Technology');
INSERT INTO company VALUES(1294,'Rainbird Software');
INSERT INTO company VALUES(1295,'Acornsoft Limited');
INSERT INTO company VALUES(1296,'Telecomsoft (U.S.)');
INSERT INTO company VALUES(1297,'Dizzy Enterprises Ltd.');
INSERT INTO company VALUES(1298,'Bethesda Softworks LLC');
INSERT INTO company VALUES(1299,'Panesian Taiwan Ltd.');
INSERT INTO company VALUES(1300,'TDK Mediactive, Inc.');
INSERT INTO company VALUES(1301,'Mindscape International GmbH');
INSERT INTO company VALUES(1302,'Isac Entertainment Corp.');
INSERT INTO company VALUES(1303,'Threshold Research');
INSERT INTO company VALUES(1304,'Magnetic Fields (Software Design) Ltd.');
INSERT INTO company VALUES(1305,'Mighty Craft Co.');
INSERT INTO company VALUES(1306,'Artech Digital Entertainments, Inc.');
INSERT INTO company VALUES(1307,'Tokuma Shoten Intermedia Inc.');
INSERT INTO company VALUES(1308,'Takeru Co., Ltd.');
INSERT INTO company VALUES(1309,'Sur de Wave');
INSERT INTO company VALUES(1310,'Human Creative Products');
INSERT INTO company VALUES(1311,'Special FX Software Ltd.');
INSERT INTO company VALUES(1312,'Magic Team');
INSERT INTO company VALUES(1313,'M&M');
INSERT INTO company VALUES(1314,'Rocket Science Productions, Inc.');
INSERT INTO company VALUES(1315,'MRH Software');
INSERT INTO company VALUES(1316,'Radioactive Software');
INSERT INTO company VALUES(1317,'NMS Software Ltd.');
INSERT INTO company VALUES(1318,'Cyclone System');
INSERT INTO company VALUES(1319,'Sol Corporation');
INSERT INTO company VALUES(1320,'Albino Frog Software, Inc.');
INSERT INTO company VALUES(1321,'Atlus');
INSERT INTO company VALUES(1322,'Megasoft');
INSERT INTO company VALUES(1323,'Myriad Games, Inc.');
INSERT INTO company VALUES(1324,'Caltron Industries, Inc.');
INSERT INTO company VALUES(1325,'Arena Graphics');
INSERT INTO company VALUES(1326,'TXC Corporation');
INSERT INTO company VALUES(1327,'Photopak S.A.');
INSERT INTO company VALUES(1328,'Gartist Team');
INSERT INTO company VALUES(1329,'Daou Infosys Corp.');
INSERT INTO company VALUES(1330,'Sierra On-Line Japan, Inc.');
INSERT INTO company VALUES(1331,'Source Research & Development Ltd.');
INSERT INTO company VALUES(1332,'Matchbox International Ltd');
INSERT INTO company VALUES(1333,'Working Designs, Inc.');
INSERT INTO company VALUES(1334,'Lucasfilm Games');
INSERT INTO company VALUES(1335,'MSI Entertainment, LLC.');
INSERT INTO company VALUES(1336,'Imagitec Design Ltd.');
INSERT INTO company VALUES(1337,'Softgold');
INSERT INTO company VALUES(1338,'Japan Soft Technology');
INSERT INTO company VALUES(1339,'Minato Giken');
INSERT INTO company VALUES(1340,'Kaga Electronics Co., Ltd.');
INSERT INTO company VALUES(1341,'Minamimachi Bugyousyo');
INSERT INTO company VALUES(1342,'SSTB - Hudson Soft');
INSERT INTO company VALUES(1343,'Amusement, Ltd.');
INSERT INTO company VALUES(1344,'ORG Corporation');
INSERT INTO company VALUES(1345,'Dennou Kenkyusho');
INSERT INTO company VALUES(1346,'Magnin & Associates');
INSERT INTO company VALUES(1347,'Ocean Europe Limited');
INSERT INTO company VALUES(1348,'FarSight Technologies Inc.');
INSERT INTO company VALUES(1349,'The Big Red Software Company Ltd.');
INSERT INTO company VALUES(1350,'Teeny Weeny Games, Ltd.');
INSERT INTO company VALUES(1351,'Gamtec Corp.');
INSERT INTO company VALUES(1352,'Open Production');
INSERT INTO company VALUES(1353,'Somari Team');
INSERT INTO company VALUES(1354,'J.Y. Company');
INSERT INTO company VALUES(1355,'Hummer Team');
INSERT INTO company VALUES(1356,'Shenzhen Nanjing Technology');
INSERT INTO company VALUES(1357,'High Level Challenge');
INSERT INTO company VALUES(1358,'Morphcat Games UG');
INSERT INTO company VALUES(1359,'Sly Dog Studios');
INSERT INTO company VALUES(1360,'Toyo Trading Co., Ltd.');
INSERT INTO company VALUES(1361,'Gradual Games');
INSERT INTO company VALUES(1362,'retroUSB');
INSERT INTO company VALUES(1363,'Infinite NES Lives');
INSERT INTO company VALUES(1364,'Active Enterprises, LLC');
INSERT INTO company VALUES(1365,'Riki');
INSERT INTO company VALUES(1366,'Retrotainment Games LLC');
INSERT INTO company VALUES(1367,'Studio Dustmop');
INSERT INTO company VALUES(1368,'Death by Audio Arcade');
INSERT INTO company VALUES(1369,'Team Yolkfolk');
INSERT INTO company VALUES(1370,'Phoenix Ware');
INSERT INTO company VALUES(1371,'Cowlitz Gamers for Kids');
INSERT INTO company VALUES(1372,'Quiquopro Games');
INSERT INTO company VALUES(1373,'AasiPelit');
INSERT INTO company VALUES(1374,'Spoony Bard Productions');
INSERT INTO company VALUES(1375,'Broke Studio');
INSERT INTO company VALUES(1376,'EmuNes');
INSERT INTO company VALUES(1377,'Bite the Chili Productions');
INSERT INTO company VALUES(1378,'Khan Games');
INSERT INTO company VALUES(1379,'8 Bit Legit');
INSERT INTO company VALUES(1380,'Dullahan Software');
INSERT INTO company VALUES(1381,'UXB');
INSERT INTO company VALUES(1382,'Implicit Conversions LLC');
INSERT INTO company VALUES(1383,'Implicit Conversions Inc.');
INSERT INTO company VALUES(1384,'FG Software');
INSERT INTO company VALUES(1385,'Nape Games S.L.');
INSERT INTO company VALUES(1386,'SJ Games');
INSERT INTO company VALUES(1387,'DaleCoop Studio');
INSERT INTO company VALUES(1388,'This Room Is An Illusion');
INSERT INTO company VALUES(1389,'Interabang Entertainment');
INSERT INTO company VALUES(1390,'The Media Indie Exchange');
INSERT INTO company VALUES(1391,'Chronicler of Legends');
INSERT INTO company VALUES(1392,'Lowtek Games');
INSERT INTO company VALUES(1393,'WAVE Game Studios');
INSERT INTO company VALUES(1394,'Raft Labs Interactive');
INSERT INTO company VALUES(1395,'Dusty Medical Records');
INSERT INTO company VALUES(1396,'Nami Tentou Mushi, LLC');
INSERT INTO company VALUES(1397,'The 6502 Collective');
INSERT INTO company VALUES(1398,'Acutis Games');
INSERT INTO company VALUES(1399,'Passe Gaming');
INSERT INTO company VALUES(1400,'Dalyen Retro Games');
INSERT INTO company VALUES(1401,'Techmaster Games');
INSERT INTO company VALUES(1402,'yyrGames');
INSERT INTO company VALUES(1403,'Locomalito');
INSERT INTO company VALUES(1404,'RetroWorks');
INSERT INTO company VALUES(1405,'Parisoft');
INSERT INTO company VALUES(1406,'PlayOnRetro');
INSERT INTO company VALUES(1407,'Lucera Project');
INSERT INTO company VALUES(1408,'Double Sided Games');
INSERT INTO company VALUES(1409,'Artix Entertainment LLC');
INSERT INTO company VALUES(1410,'Rigg''d Games');
INSERT INTO company VALUES(1411,'VGNYsoft');
INSERT INTO company VALUES(1412,'CrazyGroupTrio Games');
INSERT INTO company VALUES(1413,'Elden Pixels ek. för.');
INSERT INTO company VALUES(1414,'TimeKey Games');
INSERT INTO company VALUES(1415,'Video Game Sage');
INSERT INTO company VALUES(1416,'Orebody Inc');
INSERT INTO company VALUES(1417,'Sinclair Research Ltd.');
INSERT INTO company VALUES(1418,'Normal Distribution LLC');
INSERT INTO company VALUES(1419,'BCI Software');
INSERT INTO company VALUES(1420,'Bitwise Reprise LLC');
INSERT INTO company VALUES(1421,'Premium Edition Games');
INSERT INTO company VALUES(1422,'Knights of Bytes');
INSERT INTO company VALUES(1423,'Protovision');
INSERT INTO company VALUES(1424,'poly.play');
INSERT INTO company VALUES(1425,'RetroBro Gaming Entertainment');
INSERT INTO company VALUES(1426,'The MIX Games');
INSERT INTO company VALUES(1427,'Wallride, LLC');
INSERT INTO company VALUES(1428,'Bidon Labs');
INSERT INTO company VALUES(1429,'DarkBits');
INSERT INTO company VALUES(1430,'Orc Face Games');
INSERT INTO company VALUES(1431,'Aeon & Star Interactive');
INSERT INTO company VALUES(1432,'Refresh Games');
INSERT INTO company VALUES(1433,'Cat Hui Trading LLC');
COMMIT;
