INSERT INTO platform VALUES(1,'SNES');
INSERT INTO platform VALUES(2,'Nintendo Switch');
INSERT INTO platform VALUES(3,'PlayStation');
INSERT INTO platform VALUES(4,'Nintendo DS');
INSERT INTO platform VALUES(5,'PSP');
INSERT INTO platform VALUES(6,'PlayStation 3');
INSERT INTO platform VALUES(7,'Wii');
INSERT INTO platform VALUES(8,'iPhone');
INSERT INTO platform VALUES(9,'Android');
INSERT INTO platform VALUES(10,'PS Vita');
INSERT INTO platform VALUES(11,'tvOS');
INSERT INTO platform VALUES(12,'iPad');
INSERT INTO platform VALUES(13,'DoJa');
INSERT INTO platform VALUES(14,'Wii U');
INSERT INTO platform VALUES(15,'New Nintendo 3DS');
INSERT INTO platform VALUES(16,'Arcade');
INSERT INTO platform VALUES(17,'Windows');
INSERT INTO platform VALUES(18,'Game Boy Advance');
INSERT INTO platform VALUES(19,'Fire OS');
INSERT INTO platform VALUES(20,'Game Boy Color');
INSERT INTO platform VALUES(21,'DOS');
INSERT INTO platform VALUES(22,'Genesis');
INSERT INTO platform VALUES(23,'Amiga');
INSERT INTO platform VALUES(24,'FM Towns');
INSERT INTO platform VALUES(25,'Sharp X68000');
INSERT INTO platform VALUES(26,'SEGA Saturn');
INSERT INTO platform VALUES(27,'Atari ST');
INSERT INTO platform VALUES(28,'Commodore 64');
INSERT INTO platform VALUES(29,'ZX Spectrum');
INSERT INTO platform VALUES(30,'Browser');
INSERT INTO platform VALUES(31,'BREW');
INSERT INTO platform VALUES(32,'Game Boy');
INSERT INTO platform VALUES(33,'NES');
INSERT INTO platform VALUES(34,'TurboGrafx-16');
INSERT INTO platform VALUES(35,'Jaguar');
INSERT INTO platform VALUES(36,'SEGA 32X');
INSERT INTO platform VALUES(37,'Game Gear');
INSERT INTO platform VALUES(38,'Nintendo 3DS');
INSERT INTO platform VALUES(39,'SEGA CD');
INSERT INTO platform VALUES(40,'SEGA Master System');
INSERT INTO platform VALUES(41,'Lynx');
INSERT INTO platform VALUES(42,'3DO');
INSERT INTO platform VALUES(43,'TurboGrafx CD');
INSERT INTO platform VALUES(44,'Amiga CD32');
INSERT INTO platform VALUES(45,'Amstrad CPC');
INSERT INTO platform VALUES(46,'J2ME');
INSERT INTO platform VALUES(47,'CD-i');
INSERT INTO platform VALUES(48,'Macintosh');
INSERT INTO platform VALUES(49,'CDTV');
INSERT INTO platform VALUES(50,'PC-98');
INSERT INTO platform VALUES(51,'Acorn 32-bit');
INSERT INTO platform VALUES(52,'SAM Coup├⌐');
INSERT INTO platform VALUES(53,'PlayStation 2');
INSERT INTO platform VALUES(54,'Apple II');
INSERT INTO platform VALUES(55,'Antstream');
INSERT INTO platform VALUES(56,'Palm OS');
INSERT INTO platform VALUES(57,'Symbian');
INSERT INTO platform VALUES(58,'BBC Micro');
INSERT INTO platform VALUES(59,'Electron');
INSERT INTO platform VALUES(60,'OS/2');
INSERT INTO platform VALUES(61,'Linux');
INSERT INTO platform VALUES(62,'Dreamcast');
INSERT INTO platform VALUES(63,'WonderSwan');
INSERT INTO platform VALUES(64,'WonderSwan Color');
INSERT INTO platform VALUES(65,'Xbox');
INSERT INTO platform VALUES(66,'Xbox 360');
INSERT INTO platform VALUES(67,'BlackBerry');
INSERT INTO platform VALUES(68,'PlayStation 4');
INSERT INTO platform VALUES(69,'Windows 16-bit');
INSERT INTO platform VALUES(70,'Neo Geo');
INSERT INTO platform VALUES(71,'Neo Geo CD');
INSERT INTO platform VALUES(72,'Windows Apps');
INSERT INTO platform VALUES(73,'Xbox One');
INSERT INTO platform VALUES(74,'Nintendo DSi');
INSERT INTO platform VALUES(75,'Apple IIgs');
INSERT INTO platform VALUES(76,'Zodiac');
INSERT INTO platform VALUES(77,'PC-88');
INSERT INTO platform VALUES(78,'MSX');
INSERT INTO platform VALUES(79,'Zeebo');
INSERT INTO platform VALUES(80,'PlayStation 5');
INSERT INTO platform VALUES(81,'Xbox Series');
INSERT INTO platform VALUES(82,'PC Booter');
INSERT INTO platform VALUES(83,'Commodore 128');
INSERT INTO platform VALUES(84,'iiRcade');
INSERT INTO platform VALUES(85,'Atari 2600');
INSERT INTO platform VALUES(86,'Atari 5200');
INSERT INTO platform VALUES(87,'Atari 7800');
INSERT INTO platform VALUES(88,'Atari 8-bit');
INSERT INTO platform VALUES(89,'VIC-20');
INSERT INTO platform VALUES(90,'TI-99/4A');
INSERT INTO platform VALUES(91,'iPod Classic');
INSERT INTO platform VALUES(92,'Dedicated console');
INSERT INTO platform VALUES(93,'PC-FX');
INSERT INTO platform VALUES(94,'Nintendo 64');
INSERT INTO platform VALUES(95,'Windows Mobile');
INSERT INTO platform VALUES(96,'Evercade');
INSERT INTO platform VALUES(97,'GP32');
INSERT INTO platform VALUES(98,'Sharp X1');
INSERT INTO platform VALUES(99,'FM-7');
INSERT INTO platform VALUES(100,'MeeGo');
INSERT INTO platform VALUES(101,'Blacknut');
INSERT INTO platform VALUES(102,'Enterprise');
INSERT INTO platform VALUES(103,'Commodore 16, Plus/4');
INSERT INTO platform VALUES(104,'Oric');
INSERT INTO platform VALUES(105,'Commodore PET/CBM');
INSERT INTO platform VALUES(106,'Sharp Zaurus');
INSERT INTO platform VALUES(107,'ColecoVision');
INSERT INTO platform VALUES(108,'Intellivision');
INSERT INTO platform VALUES(109,'TRS-80');
INSERT INTO platform VALUES(110,'TRS-80 CoCo');
INSERT INTO platform VALUES(111,'Odyssey 2');
INSERT INTO platform VALUES(112,'Dragon 32/64');
INSERT INTO platform VALUES(113,'Windows Phone');
INSERT INTO platform VALUES(114,'ZX81');
INSERT INTO platform VALUES(115,'PC-6001');
INSERT INTO platform VALUES(116,'Tomy Tutor');
INSERT INTO platform VALUES(117,'Timex Sinclair 2068');
INSERT INTO platform VALUES(118,'Sharp MZ-80B/2000/2500');
INSERT INTO platform VALUES(119,'Neo Geo Pocket Color');
INSERT INTO platform VALUES(120,'Game.Com');
INSERT INTO platform VALUES(121,'Nintendo Famicom & Entertainment System');
INSERT INTO platform VALUES(122,'Nintendo Entertainment System');
INSERT INTO platform VALUES(123,'Super Nintendo Entertainment System');
INSERT INTO platform VALUES(124,'Coleco Adam');
INSERT INTO platform VALUES(125,'Dedicated handheld');
INSERT INTO platform VALUES(126,'PC-8000');
INSERT INTO platform VALUES(127,'Sharp MZ-80K/700/800/1500');
INSERT INTO platform VALUES(128,'SG-1000');
INSERT INTO platform VALUES(129,'Hitachi S1');
INSERT INTO platform VALUES(130,'SMC-777');
INSERT INTO platform VALUES(131,'Sord M5');
INSERT INTO platform VALUES(132,'Epoch Super Cassette Vision');
INSERT INTO platform VALUES(133,'Roku');
INSERT INTO platform VALUES(134,'Terminal');
INSERT INTO platform VALUES(135,'Casio PV-1000');
INSERT INTO platform VALUES(136,'Toshiba Pasopia');
INSERT INTO platform VALUES(137,'GameCube');
INSERT INTO platform VALUES(138,'Spectravideo');
INSERT INTO platform VALUES(139,'Mattel Aquarius');
INSERT INTO platform VALUES(140,'Thomson TO');
INSERT INTO platform VALUES(141,'Thomson MO');
INSERT INTO platform VALUES(142,'Arcadia 2001');
INSERT INTO platform VALUES(143,'Plex Arcade');
INSERT INTO platform VALUES(144,'Tatung Einstein');
INSERT INTO platform VALUES(145,'Mophun');
INSERT INTO platform VALUES(146,'Supervision');
INSERT INTO platform VALUES(147,'Amstrad PCW');
INSERT INTO platform VALUES(148,'Maemo');
INSERT INTO platform VALUES(149,'Playdate');
INSERT INTO platform VALUES(150,'Ouya');
