INSERT INTO genre VALUES(1,'Action');
INSERT INTO genre VALUES(2,'Side view');
INSERT INTO genre VALUES(3,'Platform');
INSERT INTO genre VALUES(4,'Compilation');
INSERT INTO genre VALUES(5,'2D scrolling');
INSERT INTO genre VALUES(6,'Direct control');
INSERT INTO genre VALUES(7,'Sci-fi / futuristic');
INSERT INTO genre VALUES(8,'Top-down');
INSERT INTO genre VALUES(9,'Role-playing (RPG)');
INSERT INTO genre VALUES(10,'Anime / Manga');
INSERT INTO genre VALUES(11,'Fantasy');
INSERT INTO genre VALUES(12,'Turn-based');
INSERT INTO genre VALUES(13,'Japanese-style RPG (JRPG)');
INSERT INTO genre VALUES(14,'Steampunk');
INSERT INTO genre VALUES(15,'Shooter');
INSERT INTO genre VALUES(16,'Metroidvania');
INSERT INTO genre VALUES(17,'Regional differences');
INSERT INTO genre VALUES(18,'Puzzle elements');
INSERT INTO genre VALUES(19,'Diagonal-down');
INSERT INTO genre VALUES(20,'Real-time');
INSERT INTO genre VALUES(21,'Menu structures');
INSERT INTO genre VALUES(22,'Arcade');
INSERT INTO genre VALUES(23,'Fighting');
INSERT INTO genre VALUES(24,'Martial arts');
INSERT INTO genre VALUES(25,'Sports');
INSERT INTO genre VALUES(26,'Isometric');
INSERT INTO genre VALUES(27,'Basketball');
INSERT INTO genre VALUES(28,'Licensed');
INSERT INTO genre VALUES(29,'Comedy');
INSERT INTO genre VALUES(30,'Strategy / tactics');
INSERT INTO genre VALUES(31,'Tactical RPG');
INSERT INTO genre VALUES(32,'Horror');
INSERT INTO genre VALUES(33,'Action RPG');
INSERT INTO genre VALUES(34,'Racing / Driving');
INSERT INTO genre VALUES(35,'Behind view');
INSERT INTO genre VALUES(36,'Automobile');
INSERT INTO genre VALUES(37,'Track racing');
INSERT INTO genre VALUES(38,'Football (American)');
INSERT INTO genre VALUES(39,'Puzzle');
INSERT INTO genre VALUES(40,'Fixed / flip-screen');
INSERT INTO genre VALUES(41,'Falling block puzzle');
INSERT INTO genre VALUES(42,'Tile matching puzzle');
INSERT INTO genre VALUES(43,'Football (European) / Soccer');
INSERT INTO genre VALUES(44,'Hockey');
INSERT INTO genre VALUES(45,'3rd-person (Other)');
INSERT INTO genre VALUES(46,'Space flight');
INSERT INTO genre VALUES(47,'Point and select');
INSERT INTO genre VALUES(48,'Simulation');
INSERT INTO genre VALUES(49,'Tennis');
INSERT INTO genre VALUES(50,'Mecha / giant robot');
INSERT INTO genre VALUES(51,'Medieval');
INSERT INTO genre VALUES(52,'Western');
INSERT INTO genre VALUES(53,'Middle East');
INSERT INTO genre VALUES(54,'Managerial / business simulation');
INSERT INTO genre VALUES(55,'Free camera');
INSERT INTO genre VALUES(56,'City building / construction simulation');
INSERT INTO genre VALUES(57,'Contemporary');
INSERT INTO genre VALUES(58,'RPG elements');
INSERT INTO genre VALUES(59,'Street racing');
INSERT INTO genre VALUES(60,'Beat ''em up / brawler');
INSERT INTO genre VALUES(61,'Flight / aviation');
INSERT INTO genre VALUES(62,'Cyberpunk / dark sci-fi');
INSERT INTO genre VALUES(63,'Vehicle simulator');
INSERT INTO genre VALUES(64,'Multiple units/characters control');
INSERT INTO genre VALUES(65,'Adventure');
INSERT INTO genre VALUES(66,'Rail shooter');
INSERT INTO genre VALUES(67,'Hovercraft');
INSERT INTO genre VALUES(68,'Boxing');
INSERT INTO genre VALUES(69,'1st-person');
INSERT INTO genre VALUES(70,'Golf');
INSERT INTO genre VALUES(71,'Healthcare');
INSERT INTO genre VALUES(72,'Interwar');
INSERT INTO genre VALUES(73,'Baseball');
INSERT INTO genre VALUES(74,'Vehicular combat');
INSERT INTO genre VALUES(75,'Cards / tiles');
INSERT INTO genre VALUES(76,'Helicopter');
INSERT INTO genre VALUES(77,'War');
INSERT INTO genre VALUES(78,'Detective / mystery');
INSERT INTO genre VALUES(79,'Oceania');
INSERT INTO genre VALUES(80,'North America');
INSERT INTO genre VALUES(81,'Japan (Ancient/Classical/Medieval)');
INSERT INTO genre VALUES(82,'Wrestling');
INSERT INTO genre VALUES(83,'4X');
INSERT INTO genre VALUES(84,'Turn-based strategy (TBS)');
INSERT INTO genre VALUES(85,'Post-apocalyptic');
INSERT INTO genre VALUES(86,'Africa');
INSERT INTO genre VALUES(87,'Motorcycle');
INSERT INTO genre VALUES(88,'Pinball');
INSERT INTO genre VALUES(89,'Real-time tactics (RTT)');
INSERT INTO genre VALUES(90,'Asia');
INSERT INTO genre VALUES(91,'Europe');
INSERT INTO genre VALUES(92,'South America');
INSERT INTO genre VALUES(93,'Japan (Modern/Futuristic)');
INSERT INTO genre VALUES(94,'Naval / watercraft');
INSERT INTO genre VALUES(95,'Age of Discovery / Enlightenment');
INSERT INTO genre VALUES(96,'Interactive fiction / text adventure');
INSERT INTO genre VALUES(97,'Visual novel');
INSERT INTO genre VALUES(98,'Ecology / nature');
INSERT INTO genre VALUES(99,'Real-time strategy (RTS)');
INSERT INTO genre VALUES(100,'Pool / snooker');
INSERT INTO genre VALUES(101,'Fishing');
INSERT INTO genre VALUES(102,'Educational');
INSERT INTO genre VALUES(103,'Music');
INSERT INTO genre VALUES(104,'Graphics / art');
INSERT INTO genre VALUES(105,'Paddle / Pong');
INSERT INTO genre VALUES(106,'Add-on');
INSERT INTO genre VALUES(107,'Story / mission');
INSERT INTO genre VALUES(108,'Off-roading');
INSERT INTO genre VALUES(109,'Historical events');
INSERT INTO genre VALUES(110,'Classical antiquity');
INSERT INTO genre VALUES(111,'Prehistoric');
INSERT INTO genre VALUES(112,'Tank');
INSERT INTO genre VALUES(113,'Board game');
INSERT INTO genre VALUES(114,'China (Ancient / Imperial)');
INSERT INTO genre VALUES(115,'Artillery');
INSERT INTO genre VALUES(116,'Bowling');
INSERT INTO genre VALUES(117,'Gambling');
INSERT INTO genre VALUES(118,'World War I');
INSERT INTO genre VALUES(119,'Word construction');
INSERT INTO genre VALUES(120,'World War II');
INSERT INTO genre VALUES(121,'Crime');
INSERT INTO genre VALUES(122,'Snowboarding / skiing');
INSERT INTO genre VALUES(123,'Olympiad / mixed sports');
INSERT INTO genre VALUES(124,'Skateboarding');
INSERT INTO genre VALUES(125,'Chess');
INSERT INTO genre VALUES(126,'Geography');
INSERT INTO genre VALUES(127,'Volleyball');
INSERT INTO genre VALUES(128,'Survival horror');
INSERT INTO genre VALUES(129,'Game show / trivia / quiz');
INSERT INTO genre VALUES(130,'History');
INSERT INTO genre VALUES(131,'Bike / bicycling');
INSERT INTO genre VALUES(132,'Surfing');
INSERT INTO genre VALUES(133,'Tricks / stunts');
INSERT INTO genre VALUES(134,'Cold War');
INSERT INTO genre VALUES(135,'Religion');
INSERT INTO genre VALUES(136,'Health / nutrition');
INSERT INTO genre VALUES(137,'Mini-games');
INSERT INTO genre VALUES(138,'Truck');
INSERT INTO genre VALUES(139,'Physical extras');
INSERT INTO genre VALUES(140,'Fangame');
INSERT INTO genre VALUES(141,'Full Motion Video (FMV)');
INSERT INTO genre VALUES(142,'Meditative / Zen');
INSERT INTO genre VALUES(143,'Foreign language');
INSERT INTO genre VALUES(144,'Cinematic camera');
INSERT INTO genre VALUES(145,'Special edition');
INSERT INTO genre VALUES(146,'Time management');
INSERT INTO genre VALUES(147,'Live action');
INSERT INTO genre VALUES(148,'Horse / derby');
INSERT INTO genre VALUES(149,'Dodgeball');
INSERT INTO genre VALUES(150,'Reading / writing');
INSERT INTO genre VALUES(151,'Pre-school / toddler');
INSERT INTO genre VALUES(152,'Math / logic');
INSERT INTO genre VALUES(153,'Japanese-style adventure');
INSERT INTO genre VALUES(154,'Roguelike');
INSERT INTO genre VALUES(155,'Party game');
INSERT INTO genre VALUES(156,'Cricket');
INSERT INTO genre VALUES(157,'Hidden object');
INSERT INTO genre VALUES(158,'Music / rhythm');
INSERT INTO genre VALUES(159,'Bus');
INSERT INTO genre VALUES(160,'Train');
INSERT INTO genre VALUES(161,'Romance');
INSERT INTO genre VALUES(162,'Dating simulation');
INSERT INTO genre VALUES(163,'Text-based / Spreadsheet');
INSERT INTO genre VALUES(164,'Egypt (Ancient)');
INSERT INTO genre VALUES(165,'Rugby');
INSERT INTO genre VALUES(166,'Hunting');
INSERT INTO genre VALUES(167,'Spy / espionage');
INSERT INTO genre VALUES(168,'Stealth');
INSERT INTO genre VALUES(169,'Text parser');
INSERT INTO genre VALUES(170,'Graphic adventure');
INSERT INTO genre VALUES(171,'Life / social simulation');
INSERT INTO genre VALUES(172,'Sea pirates / Caribbean');
INSERT INTO genre VALUES(173,'Ping pong / table tennis');
INSERT INTO genre VALUES(174,'Extra content / game');
INSERT INTO genre VALUES(175,'Paintball');
INSERT INTO genre VALUES(176,'Industrial Age');
INSERT INTO genre VALUES(177,'Sandbox / open world');
INSERT INTO genre VALUES(178,'Map / level');
INSERT INTO genre VALUES(179,'Darts / target shooting');
INSERT INTO genre VALUES(180,'Quick Time Events (QTEs)');
INSERT INTO genre VALUES(181,'Mental training');
INSERT INTO genre VALUES(182,'Alternate history');
INSERT INTO genre VALUES(183,'Wargame');
INSERT INTO genre VALUES(184,'Athletics');
INSERT INTO genre VALUES(185,'Hack and slash');
